// by snowcat 12 15 1997

// this shared file is used at several places. 

mapping obstacles = ([
  "jz"         : "  1. 江州府／金山寺",
  "sc"         : "  2. 双叉岭",
  "yj"         : "  3. 鹰愁涧",
  "hf"         : "  4. 黑风山／观音院",
  "yz"         : "  5. 高老庄／云栈洞",
  "huangfeng"  : "  6. 黄风岭",
  "liusha"     : "  7. 流沙河",
  "village"    : "  8. 四圣试禅心",
  "wuzhuang"   : "  9. 五庄观／人参果",
  "baigudong"  : " 10. 白骨山／白骨洞",
  "baoxiang"   : " 11. 宝象国／碗子山",
  "pingding"   : " 12. 平顶山／莲花洞／压龙山／压龙洞",
  "wuji"       : " 13. 乌鸡国／宝林寺",
  "huoyun"     : " 14. 枯松涧／火云洞",
  "chechi"     : " 15. 车迟国／三清观",
  "tongtian"   : " 16. 通天河／陈家庄",
  "jindou"     : " 17. 金兜山／金兜洞",
  "nuerguo"    : " 18. 女儿国／解阳山",
  "dudi"       : " 19. 毒敌山／琵琶洞",
  "firemount"  : " 20. 火焰山／翠云山",
  "jilei"      : " 21. 积雷山／摩云洞",
  "jisaiguo"   : " 22. 祭赛国／碧波潭",
  "jingjiling" : " 23. 荆棘岭／木仙庵",
  "xiaoxitian" : " 24. 小西天／小雷音寺",
  "zhuzi"      : " 25. 朱紫国／麒麟山／獬豸洞",
  "pansi"      : " 26. 盘丝岭／盘丝洞／黄花观／紫云山",
  "biqiu"      : " 27. 比丘国／清华庄／清华洞",
  "liuer-mihou": " 28. 花果山／真假猴王",
  "wudidong"   : " 29. 无底洞／黑松林",
  "qinfa"      : " 30. 钦法国",
  "yinwu"      : " 31. 隐雾山／连环洞",
  "fengxian"   : " 32. 凤仙郡",
  "yuhua"      : " 33. 玉华县／豹头山／虎口洞／竹节山／九曲盘桓洞",
  "jinping"    : " 34. 金平府／青龙山／玄英洞",
  "tianzhu"    : " 35. 天竺国／毛颖山／三连穴",
  "niulang"    : " 36. 鹊桥相会",
 "shenglingzhu": " 37. 圣灵珠",
  "shushan"  : " 38. 镇妖塔救灵儿", 
]);
