//normal

mapping *renwu1=({
([	"type":1,	"id":"fei fei",	"name":"肥肥",	"lv":3,	]),
([	"type":1,	"id":"guafu",		"name":"寡妇",	"lv":3,	]),
([	"type":1,	"id":"lao cai",	"name":"老材",	"lv":3,	]),
([	"type":1,	"id":"men wei",	"name":"门卫",	"lv":4,	]),
([	"type":1,	"id":"xiao shanzei","name":"小山贼",	"lv":2,	]),
([	"type":1,	"id":"shan zei",	"name":"山贼",	"lv":4,	]),
([	"type":1,	"id":"tongzi",	"name":"陪练童子",	"lv":3,	]),
([	"type":1,	"id":"white lady",	"name":"白衣少女",	"lv":2,	]),
([	"type":1,	"id":"guan jia",	"name":"管家",	"lv":2,	]),
([	"type":1,	"id":"jia ding",	"name":"家丁",	"lv":2,	]),
([	"type":1,	"id":"lao lanyan",	"name":"老烂眼",	"lv":4,	]),
([	"type":1,	"id":"liu mang",	"name":"流氓",	"lv":2,	]),
([	"type":1,	"id":"liumang tou",	"name":"流氓头",	"lv":3,	]),
([	"type":1,	"id":"qigai",		"name":"乞丐",	"lv":2,	]),
([	"type":1,	"id":"shusheng",	"name":"书生",	"lv":1,	]),
([	"type":1,	"id":"tufei",		"name":"土匪",	"lv":3,	]),
([	"type":1,	"id":"xiaohuozi",	"name":"小伙子",	"lv":1,	]),
([	"type":1,	"id":"xiao lanyan",	"name":"小烂眼",	"lv":1,	]),
([	"type":1,	"id":"e nu",		"name":"恶奴",	"lv":4,	]),
([	"type":1,	"id":"maque",		"name":"麻雀",	"lv":1,	]),
([	"type":1,	"id":"jiao tu",	"name":"日月教教徒","lv":1,	]),
([	"type":1,	"id":"shi nu",	"name":"侍女",	"lv":3,	]),
([	"type":1,	"id":"shi nu",	"name":"慌张的侍女","lv":3,	]),
([	"type":1,	"id":"wolf2",		"name":"狼",		"lv":2,	]),
([	"type":1,	"id":"zishan shizhe","name":"紫衫侍者",	"lv":6,	]),
([	"type":1,	"id":"xiao taijian","name":"小太监",	"lv":3,	]),
([	"type":1,	"id":"xiao guizi",	"name":"小桂子",	"lv":1,	]),
([	"type":1,	"id":"ya huan",	"name":"王府丫鬟",	"lv":1,	]),
([	"type":1,	"id":"ma fu",		"name":"王府马夫",	"lv":4,	]),
([	"type":1,	"id":"rui chu",	"name":"蕊初",	"lv":1,	]),
([	"type":1,	"id":"guard",		"name":"城卫兵",	"lv":4,	]),
([	"type":1,	"id":"huabo siji",	"name":"华伯斯基",	"lv":3,	]),
([	"type":1,	"id":"jia ding",	"name":"王府家丁",	"lv":3,	]),
([	"type":1,	"id":"lao guanjia",	"name":"老管家",	"lv":4,	]),
([	"type":1,	"id":"zhong wuli",	"name":"钟无离",	"lv":3,	]),
([	"type":1,	"id":"liu youkong",	"name":"柳有孔",	"lv":2,	]),
([	"type":1,	"id":"fu",		"name":"符永祥",	"lv":3,	]),
([	"type":1,	"id":"xue jinyin",	"name":"薛金英",	"lv":2,	]),
([	"type":1,	"id":"zhan qili",	"name":"战其力",	"lv":3,	]),
([	"type":1,	"id":"dahan",		"name":"蓝衣大汉",	"lv":2,	]),
([	"type":1,	"id":"hekun",		"name":"何昆",	"lv":2,	]),
([	"type":1,	"id":"chen",		"name":"秤千金",	"lv":2,	]),
([	"type":1,	"id":"guan",		"name":"管八方",	"lv":2,	]),
([	"type":1,	"id":"tang rou",	"name":"唐柔",	"lv":4,	]),
([	"type":1,	"id":"chuan fu",	"name":"船夫",	"lv":2,	]),
([	"type":1,	"id":"chike",		"name":"吃客",	"lv":1,	]),
([	"type":1,	"id":"dashou",	"name":"看场打手",	"lv":4,	]),
([	"type":1,	"id":"gongzi ge",	"name":"公子哥",	"lv":1,	]),
([	"type":1,	"id":"dashou",	"name":"赌场打手",	"lv":4,	]),
([	"type":1,	"id":"laobao",	"name":"老鸨",	"lv":2,	]),
([	"type":1,	"id":"popi",		"name":"泼皮",	"lv":2,	]),
([	"type":1,	"id":"wulai",		"name":"无赖",	"lv":2,	]),
([	"type":1,	"id":"zhang san",	"name":"混混张三",	"lv":4,	]),
([	"type":1,	"id":"tongnan",	"name":"童男",	"lv":1,	]),
([	"type":1,	"id":"tongnu",	"name":"童女",	"lv":1,	]),
([	"type":1,	"id":"xiao tong",	"name":"小童",	"lv":1,	]),
([	"type":1,	"id":"xingren",	"name":"行人",	"lv":1,	]),
([	"type":1,	"id":"huyuan",	"name":"护院",	"lv":4,	]),
([	"type":1,	"id":"nupu",		"name":"奴仆",	"lv":2,	]),
([	"type":1,	"id":"dizi",		"name":"无聊弟子",	"lv":3,	]),
([	"type":1,	"id":"wushi",		"name":"巫士",	"lv":3,	]),
([	"type":1,	"id":"dipi",		"name":"地痞",	"lv":1,	]),
([	"type":1,	"id":"hou yuanwai",	"name":"侯员外",	"lv":4,	]),
([	"type":1,	"id":"gai yiming",	"name":"盖一鸣",	"lv":4,	]),
([	"type":1,	"id":"dashou",	"name":"雇佣打手",	"lv":2,	]),
([	"type":1,	"id":"tu fei",	"name":"土匪",	"lv":4,	]),
([	"type":1,	"id":"yuzu",		"name":"狱卒",	"lv":4,	]),
([	"type":1,	"id":"bi nu",		"name":"婢女",	"lv":3,	]),
([	"type":1,	"id":"yan mama",	"name":"严妈妈",	"lv":3,	]),
([	"type":1,	"id":"gu",		"name":"老顾头",	"lv":3,	]),
([	"type":1,	"id":"nu tong",	"name":"女童",	"lv":1,	]),
([	"type":1,	"id":"nan tong",	"name":"男童",	"lv":1,	]),
([	"type":1,	"id":"nu pu",		"name":"女仆",	"lv":3,	]),
([	"type":1,	"id":"nan pu",	"name":"男仆",	"lv":3,	]),
([	"type":1,	"id":"dao ke",	"name":"刀客",	"lv":5,	]),
([	"type":1,	"id":"jian ke",	"name":"剑客",	"lv":5,	]),
([	"type":1,	"id":"tangzi shou",	"name":"趟子手",	"lv":4,	]),
([	"type":1,	"id":"xiao louluo",	"name":"小喽罗",	"lv":1,	]),
([	"type":1,	"id":"xiao tufei",	"name":"小土匪",	"lv":1,	]),
([	"type":1,	"id":"mentu",		"name":"门徒",	"lv":3,	]),
([	"type":1,	"id":"sun",		"name":"孙癞子",	"lv":2,	]),
([	"type":1,	"id":"jian shang",	"name":"奸商",	"lv":2,	]),
([	"type":1,	"id":"yanyuan",	"name":"男演员",	"lv":1,	]),
([	"type":1,	"id":"yanyuan",	"name":"女演员",	"lv":1,	]),
([	"type":1,	"id":"yitai",		"name":"姨太太",	"lv":1,	]),

([	"type":1,	"id":"da han",	"name":"明教大汉",	"lv":4,	]),
([	"type":1,	"id":"cun gu",	"name":"村姑",	"lv":2,	]),
([	"type":1,	"id":"man",		"name":"农民",	"lv":2,	]),
([	"type":1,	"id":"qiao fu",	"name":"樵夫",	"lv":1,	]),
([	"type":1,	"id":"woman",		"name":"农家妇女",	"lv":2,	]),
([	"type":1,	"id":"ya huan",	"name":"丫环",	"lv":1,	]),
([	"type":1,	"id":"zhang ma",	"name":"张妈",	"lv":1,	]),
([	"type":1,	"id":"biao tou",	"name":"镖头",	"lv":2,	]),
([	"type":1,	"id":"guan bing",	"name":"官兵",	"lv":4,	]),
([	"type":1,	"id":"flower girl",	"name":"卖花姑娘",	"lv":2,	]),
([	"type":1,	"id":"yaopu huoji",	"name":"药铺伙计",	"lv":2,	]),
([	"type":1,	"id":"sao muren",	"name":"扫墓人",	"lv":1,	]),
([	"type":1,	"id":"seng ren",	"name":"游方和尚",	"lv":4,	]),
([	"type":1,	"id":"wei bing",	"name":"卫兵",	"lv":4,	]),
([	"type":1,	"id":"xiao heshang","name":"小和尚",	"lv":1,	]),
([	"type":1,	"id":"ya yi",		"name":"衙役",	"lv":3,	]),
([	"type":1,	"id":"yi ren",	"name":"游方艺人",	"lv":1,	]),
([	"type":1,	"id":"zhike seng",	"name":"知客僧",	"lv":3,	]),
([	"type":1,	"id":"biao tou",	"name":"「平通镖局」镖头",	"lv":3,]),
([	"type":1,	"id":"shi bing",	"name":"士兵",	"lv":4,	]),
([	"type":1,	"id":"shang fan",	"name":"台夷商贩",	"lv":2,	]),
([	"type":1,	"id":"caisang nu",	"name":"采桑女",	"lv":3,	]),
([	"type":1,	"id":"fangsha nu",	"name":"纺纱女",	"lv":1,	]),
([	"type":1,	"id":"girl",		"name":"摆夷女子",	"lv":3,	]),
([	"type":1,	"id":"girl",		"name":"南国姑娘",	"lv":2,	]),
([	"type":1,	"id":"gong nu",	"name":"宫女",	"lv":3,	]),
([	"type":1,	"id":"gu niang",	"name":"台夷姑娘",	"lv":3,	]),
([	"type":1,	"id":"yanghua nu",	"name":"养花女",	"lv":3,	]),
([	"type":1,	"id":"jianghu yiren","name":"江湖艺人",	"lv":5,	]),
([	"type":1,	"id":"kanzhu ren",	"name":"砍竹人",	"lv":2,	]),
([	"type":1,	"id":"ke shang",	"name":"盛皮罗客商","lv":3,	]),
([	"type":1,	"id":"lao jisi",	"name":"乌夷老祭司","lv":3,	]),
([	"type":1,	"id":"lie ren",	"name":"猎人",	"lv":4,	]),
([	"type":1,	"id":"shao nu",	"name":"少女",	"lv":3,	]),
([	"type":1,	"id":"shennong dizi","name":"神农帮弟子","lv":4,	]),
([	"type":1,	"id":"shi zhe",	"name":"侍者",	"lv":4,	]),
([	"type":1,	"id":"tai jian",	"name":"太监",	"lv":3,	]),
([	"type":1,	"id":"wei shi",	"name":"素衣卫士",	"lv":4,	]),
([	"type":1,	"id":"wuliang dizi","name":"无量剑弟子","lv":4,	]),
([	"type":1,	"id":"yangcan nu",	"name":"养蚕女",	"lv":3,	]),
([	"type":1,	"id":"shoubei",	"name":"守备",	"lv":3,	]),
([	"type":1,	"id":"wuguan dizi",	"name":"武馆弟子",	"lv":1,	]),
([	"type":1,	"id":"xingshang",	"name":"行商",	"lv":2,	]),
([	"type":1,	"id":"jia ding",	"name":"王府家丁",	"lv":3,	]),
([	"type":1,	"id":"lao guanjia",	"name":"老管家",	"lv":4,	]),
([	"type":1,	"id":"wushi",		"name":"胖大武士",	"lv":4,	]),
([	"type":1,	"id":"ma fu",		"name":"王府马夫",	"lv":3,	]),
([	"type":1,	"id":"guard",		"name":"城卫兵",	"lv":4,	]),
([	"type":1,	"id":"deng yuhan",	"name":"邓玉函",	"lv":4,	]),
([	"type":1,	"id":"qiu nangu",	"name":"邱南顾",	"lv":4,	]),
([	"type":1,	"id":"qiu bo",	"name":"丘伯",	"lv":4,	]),
([	"type":1,	"id":"tie xinyue",	"name":"铁心月",	"lv":4,	]),
([	"type":1,	"id":"xiao",		"name":"萧秋水",	"lv":4,	]),
([	"type":1,	"id":"zuo qiu",	"name":"左丘超然",	"lv":4,	]),
([	"type":1,	"id":"jianghu haoke","name":"江湖豪客",	"lv":2,	]),
([	"type":1,	"id":"shao nv",	"name":"回族少女",	"lv":2,	]),
([	"type":1,	"id":"zhan shi",	"name":"回族战士",	"lv":4,	]),
([	"type":1,	"id":"chengwei",	"name":"城卫",	"lv":4,	]),
([	"type":1,	"id":"man",		"name":"卖菜汉子",	"lv":1,	]),
([	"type":1,	"id":"li si",		"name":"李四",	"lv":3,	]),
([	"type":1,	"id":"old woman",	"name":"烧香老太",	"lv":2,	]),
([	"type":1,	"id":"seng ren",	"name":"烧火僧人",	"lv":1,	]),
([	"type":1,	"id":"woman",		"name":"踏青妇人",	"lv":2,	]),
([	"type":1,	"id":"qingyi xiaotong","name":"青衣小童","lv":4,	]),
([	"type":1,	"id":"tong",		"name":"道童",	"lv":4,	]),
([	"type":1,	"id":"dibao",		"name":"地保",	"lv":2,	]),
([	"type":1,	"id":"poor man",	"name":"穷汉",	"lv":1,	]),
([	"type":1,	"id":"xiang ke",	"name":"香客",	"lv":2,	]),
([	"type":1,	"id":"old woman",	"name":"瞎眼老婆婆","lv":3,	]),
([	"type":1,	"id":"sansao",	"name":"张三嫂",	"lv":5,	]),
([	"type":1,	"id":"bao buliang",	"name":"包不靓",	"lv":4,	]),
([	"type":1,	"id":"bingyong",	"name":"兵勇",	"lv":1,	]),
([	"type":1,	"id":"chang gong",	"name":"长工",	"lv":1,	]),
([	"type":1,	"id":"da dizi",	"name":"大弟子",	"lv":4,	]),
([	"type":1,	"id":"dizi",		"name":"弟子",	"lv":3,	]),
([	"type":1,	"id":"wuseng",	"name":"护塔武僧",	"lv":3,	]),
([	"type":1,	"id":"jinxiang ke",	"name":"进香客",	"lv":2,	]),
([	"type":1,	"id":"xin nan",	"name":"信男",	"lv":3,	]),
([	"type":1,	"id":"xin nu",	"name":"信女",	"lv":2,	]),
([	"type":1,	"id":"gu",		"name":"老顾头",	"lv":3,	]),
([	"type":1,	"id":"zhike daozhang","name":"知客道长","lv":4,	]),
([	"type":1,	"id":"dizi",		"name":"山庄弟子",	"lv":3,	]),
([	"type":1,	"id":"fa kong",	"name":"法空",	"lv":4,	]),
([	"type":1,	"id":"lao wang",	"name":"老王头",	"lv":3,	]),
([	"type":1,	"id":"shang tianyi","name":"尚天一",	"lv":4,	]),
([	"type":1,	"id":"xie lin",	"name":"谢琳",	"lv":4,	]),
([	"type":1,	"id":"tanger",	"name":"棠儿",	"lv":2,	]),
([	"type":1,	"id":"chuanjia",	"name":"船家",	"lv":3,	]),
([	"type":1,	"id":"kanke",		"name":"书场看客",	"lv":3,	]),
([	"type":1,	"id":"zhuchi",	"name":"惠通",	"lv":4,	]),

([	"type":2,	"id":"chang pao",		"name":"白色长袍",		"lv":2,]),
([	"type":2,	"id":"cao mei",		"name":"草莓",		"lv":1,]),
([	"type":2,	"id":"chai",			"name":"柴",			"lv":1,]),
([	"type":2,	"id":"cai dao",		"name":"柴刀",		"lv":2,]),
([	"type":2,	"id":"fen",			"name":"蛇胆粉",		"lv":1,]),
([	"type":2,	"id":"jin",			"name":"金蛇胆",		"lv":2,]),
([	"type":2,	"id":"qing",			"name":"青蛇胆",		"lv":2,]),
([	"type":2,	"id":"she rou",		"name":"蛇肉",		"lv":1,]),
([	"type":2,	"id":"shoe",			"name":"绣花鞋",		"lv":1,]),
([	"type":2,	"id":"tu rou",		"name":"兔肉",		"lv":1,]),
([	"type":2,	"id":"gangzhang",		"name":"钢杖",		"lv":1,]),
([	"type":2,	"id":"pi beixin",		"name":"皮背心",		"lv":1,]),
([	"type":2,	"id":"sandals",		"name":"草鞋",		"lv":1,]),
([	"type":2,	"id":"dabaicai",		"name":"大白菜",		"lv":1,]),
([	"type":2,	"id":"duanjian",		"name":"短剑",		"lv":1,]),
([	"type":2,	"id":"flower shoes",	"name":"绣花小鞋",		"lv":1,]),
([	"type":2,	"id":"gou pi",		"name":"狗皮",		"lv":1,]),
([	"type":2,	"id":"gou rou",		"name":"红烧狗肉",		"lv":1,]),
([	"type":2,	"id":"hammer",		"name":"铁锤",		"lv":1,]),
([	"type":2,	"id":"jiudai",		"name":"花雕酒袋",		"lv":1,]),
([	"type":2,	"id":"jinchuang yao",	"name":"金创药",		"lv":1,]),
([	"type":2,	"id":"kaoya",			"name":"烤鸭",		"lv":1,]),
([	"type":2,	"id":"budai",			"name":"麻布袋",		"lv":1,]),
([	"type":2,	"id":"piang",			"name":"夫妻肺片",		"lv":1,]),
([	"type":2,	"id":"qingcai",		"name":"青菜",		"lv":1,]),
([	"type":2,	"id":"guoqiao mixian",	"name":"过桥米线",		"lv":1,]),
([	"type":2,	"id":"qiguo ji",		"name":"汽锅鸡",		"lv":1,]),
([	"type":2,	"id":"stone",			"name":"大理石",		"lv":1,]),
([	"type":2,	"id":"white cloth",		"name":"白绸衫",		"lv":1,]),
([	"type":2,	"id":"xiao ao",		"name":"圆领小袄",		"lv":1,]),
([	"type":2,	"id":"bocai fentiao",	"name":"菠菜粉条",		"lv":1,]),
([	"type":2,	"id":"qing hulu",		"name":"青葫芦",		"lv":1,]),
([	"type":2,	"id":"liuli qiezi",		"name":"琉璃茄子",		"lv":1,]),
([	"type":2,	"id":"mala doufu",		"name":"麻辣豆腐",		"lv":1,]),
([	"type":2,	"id":"qingshui hulu",	"name":"清水葫芦",		"lv":1,]),
([	"type":2,	"id":"shanhu baicai",	"name":"珊瑚白菜",		"lv":1,]),
([	"type":2,	"id":"zhudao",		"name":"竹刀",		"lv":1,]),
([	"type":2,	"id":"zhujian",		"name":"竹剑",		"lv":1,]),
([	"type":2,	"id":"zhuye",			"name":"竹叶",		"lv":1,]),
([	"type":2,	"id":"saozhou",		"name":"扫帚",		"lv":2,]),
([	"type":2,	"id":"cloth",			"name":"蓑衣",		"lv":1,]),
([	"type":2,	"id":"shuzhi",		"name":"树枝",		"lv":1,]),
([	"type":2,	"id":"tao shuzhi",		"name":"桃树枝",		"lv":1,]),
([	"type":2,	"id":"jiutan",		"name":"白瓷酒坛",		"lv":1,]),
([	"type":2,	"id":"zichou shan",		"name":"紫绸衫",		"lv":1,]),
([	"type":2,	"id":"qian cenggao",	"name":"千层糕",		"lv":1,]),
([	"type":2,	"id":"shao bing",		"name":"肉末烧饼",		"lv":1,]),
([	"type":2,	"id":"wandou huang",	"name":"豌豆黄",		"lv":1,]),
([	"type":2,	"id":"xiao shaomai",	"name":"小烧麦",		"lv":1,]),
([	"type":2,	"id":"rou",			"name":"蒜泥白切肉",	"lv":1,]),
([	"type":2,	"id":"bazhen gao",		"name":"八珍糕",		"lv":1,]),
([	"type":2,	"id":"congyou baocui",	"name":"葱油薄脆",		"lv":1,]),
([	"type":2,	"id":"diao pi",		"name":"貂皮",		"lv":1,]),
([	"type":2,	"id":"gongyu gan",		"name":"弓鱼干",		"lv":1,]),
([	"type":2,	"id":"jiangbao niurou",	"name":"酱爆牛肉",		"lv":1,]),
([	"type":2,	"id":"tangpen",		"name":"荷花汤盆",		"lv":1,]),
([	"type":2,	"id":"gao",			"name":"玫瑰绿豆糕",	"lv":1,]),
([	"type":2,	"id":"cloth",			"name":"摔角粗衣",		"lv":1,]),
([	"type":2,	"id":"xiaren",		"name":"清炒虾仁",		"lv":1,]),
([	"type":2,	"id":"zaoliu yupian",	"name":"糟溜鱼片",		"lv":1,]),
([	"type":2,	"id":"yaorou",		"name":"镇江肴肉",		"lv":1,]),
([	"type":2,	"id":"meat",			"name":"羊肉",		"lv":1,]),
([	"type":2,	"id":"biandan",		"name":"扁担",		"lv":1,]),
([	"type":2,	"id":"caoxie",		"name":"草鞋",		"lv":1,]),
([	"type":2,	"id":"cai dao",		"name":"菜刀",		"lv":1,]),
([	"type":2,	"id":"cai kuang",		"name":"菜筐子",		"lv":1,]),
([	"type":2,	"id":"chaihe",		"name":"柴禾",		"lv":2,]),
([	"type":2,	"id":"chang pao",		"name":"长袍",		"lv":1,]),
([	"type":2,	"id":"jiudai",		"name":"牛皮酒袋",		"lv":1,]),
([	"type":2,	"id":"baicai",		"name":"翡翠白菜",		"lv":1,]),
([	"type":2,	"id":"gangding",		"name":"钢钉",		"lv":1,]),
([	"type":2,	"id":"gangzhang",		"name":"精钢杖",		"lv":1,]),
([	"type":2,	"id":"cloth",			"name":"白布长袍",		"lv":1,]),
([	"type":2,	"id":"tie beixin",		"name":"铁背心",		"lv":1,]),
([	"type":2,	"id":"chan zhang",		"name":"禅杖",		"lv":1,]),
([	"type":2,	"id":"feibiao",		"name":"飞镖",		"lv":1,]),
([	"type":2,	"id":"lingshen san",	"name":"灵神散",		"lv":1,]),
([	"type":2,	"id":"liushen wan",		"name":"六神丸",		"lv":1,]),
([	"type":2,	"id":"nianhua san",		"name":"拈花散",		"lv":1,]),
([	"type":2,	"id":"sanqing dan",		"name":"三清丹",		"lv":1,]),
([	"type":2,	"id":"sanzijing",		"name":"三字经",		"lv":1,]),
([	"type":2,	"id":"cloth",			"name":"长衫",		"lv":2,]),
([	"type":2,	"id":"xiaojing dan",	"name":"小精丹",		"lv":1,]),
([	"type":2,	"id":"xuqi wan",		"name":"虚气丸",		"lv":1,]),
([	"type":2,	"id":"zhengqi wan",		"name":"正气丸",		"lv":1,]),
([	"type":2,	"id":"shanzi",		"name":"檀香扇",		"lv":2,]),
([	"type":2,	"id":"chuanjiang",		"name":"船浆",		"lv":1,]),
([	"type":2,	"id":"jiandao",		"name":"花剪",		"lv":1,]),
([	"type":2,	"id":"penghu",		"name":"喷壶",		"lv":1,]),
([	"type":2,	"id":"xiang",			"name":"香",			"lv":1,]),
([	"type":2,	"id":"tao",			"name":"水蜜桃",		"lv":2,]),
([	"type":2,	"id":"duan shan",		"name":"短衫",		"lv":1,]),
([	"type":2,	"id":"huashengmi",		"name":"花生米",		"lv":1,]),
([	"type":2,	"id":"hu pi",			"name":"虎皮",		"lv":1,]),
([	"type":2,	"id":"lang pi",		"name":"狼皮",		"lv":1,]),
([	"type":2,	"id":"lie zhuang",		"name":"猎装",		"lv":1,]),
([	"type":2,	"id":"putuan",		"name":"蒲团",		"lv":1,]),
([	"type":2,	"id":"ren shen",		"name":"人参",		"lv":1,]),
([	"type":2,	"id":"yangjing dan",	"name":"养精丹",		"lv":1,]),
([	"type":2,	"id":"yanshuie",		"name":"盐水鹅",		"lv":1,]),
([	"type":2,	"id":"zhuye",			"name":"竹叶",		"lv":1,]),
([	"type":2,	"id":"niu rou",		"name":"牛肉",		"lv":1,]),
([	"type":2,	"id":"you deng",		"name":"油灯",		"lv":1,]),
([	"type":2,	"id":"doufu",			"name":"豆腐",		"lv":1,]),
([	"type":2,	"id":"doufu",			"name":"家常豆腐",		"lv":1,]),
([	"type":2,	"id":"lajiao",		"name":"辣椒",		"lv":1,]),
([	"type":2,	"id":"tu rou",		"name":"红烧兔肉",		"lv":1,]),
([	"type":2,	"id":"xiangyou",		"name":"香油",		"lv":1,]),
([	"type":2,	"id":"yan",			"name":"盐巴",		"lv":1,]),
([	"type":2,	"id":"jiangyou",		"name":"酱油",		"lv":1,]),

(["type":3,	"id":"/d/baituo/damen",		"name":"白驼山大门",	"lv":2,]),
(["type":3,	"id":"/d/baituo/liangong",		"name":"白驼山练功场",	"lv":2,]),
(["type":3,	"id":"/d/baituo/fende",		"name":"坟地",		"lv":2,]),
(["type":3,	"id":"/d/chengdu/zhanbu",		"name":"占卜铺子",		"lv":2,]),
(["type":3,	"id":"/d/chengdu/guangchang",	"name":"天府广场",		"lv":2,]),
(["type":3,	"id":"/d/dali/dalinorth",		"name":"大理城北",		"lv":2,]),
(["type":3,	"id":"/d/dali/pengfu",		"name":"梁府",		"lv":2,]),
(["type":3,	"id":"/d/dali/yuxuguan",		"name":"玉虚观",		"lv":2,]),
(["type":3,	"id":"/d/tianlongsi/yaotai",	"name":"清都瑶台",		"lv":2,]),
(["type":3,	"id":"/d/hangzhou/wuchang",	"name":"石龙武场",		"lv":1,]),
(["type":3,	"id":"/d/hangzhou/santan",		"name":"三潭印月",		"lv":1,]),
(["type":3,	"id":"/d/hangzhou/pinghu",		"name":"平湖秋月",		"lv":1,]),
(["type":3,	"id":"/d/hangzhou/suci",		"name":"苏堤春晓",		"lv":1,]),
(["type":3,	"id":"/d/hangzhou/bibo",		"name":"碧波桥",		"lv":1,]),
(["type":3,	"id":"/d/heimuya/road1",		"name":"乱石坡",		"lv":2,]),
(["type":3,	"id":"/d/heimuya/xingxingtan",	"name":"猩猩滩",		"lv":2,]),
(["type":3,	"id":"/d/hengshan/xinlongxia",	"name":"金龙峡",		"lv":2,]),
(["type":3,	"id":"/d/huanggon/yongdingmen",	"name":"永定门",		"lv":1,]),
(["type":3,	"id":"/d/huanggon/miaofa",		"name":"妙法莲花寺",	"lv":1,]),
(["type":3,	"id":"/d/huanggon/qianfengyin",	"name":"前锋营",		"lv":1,]),
(["type":3,	"id":"/d/huanggon/gardon",		"name":"王府花园",		"lv":1,]),
(["type":3,	"id":"/d/huanggon/jingdukezhan",	"name":"京都客栈",		"lv":1,]),
(["type":3,	"id":"/d/huanggon/wyshanzhuang",	"name":"忘逸山庄",		"lv":1,]),
(["type":3,	"id":"/d/huanggon/shenwumen",	"name":"神武门",		"lv":1,]),
(["type":3,	"id":"/d/huanggon/qianqiutin",	"name":"千秋亭",		"lv":1,]),
(["type":3,	"id":"/d/huanggon/tiananmen",	"name":"天安门",		"lv":1,]),
(["type":3,	"id":"/d/huanggon/jiaoqiying",	"name":"骁骑营",		"lv":1,]),
(["type":3,	"id":"/d/huanggon/qingmutang",	"name":"青木堂口",		"lv":1,]),
(["type":3,	"id":"/d/huashan/shanhongpb",	"name":"山洪瀑布",		"lv":2,]),
(["type":3,	"id":"/d/huashan/baichi",		"name":"百尺峡",		"lv":2,]),
(["type":3,	"id":"/d/huashan/husun",		"name":"猢狲愁",		"lv":2,]),
(["type":3,	"id":"/d/huashan/yuntai",		"name":"云台峰",		"lv":2,]),
(["type":3,	"id":"/d/huashan/sheshen",		"name":"舍身崖",		"lv":2,]),
(["type":3,	"id":"/d/huizhu/jiayuguan",	"name":"嘉峪关",		"lv":1,]),
(["type":3,	"id":"/d/huizhu/xingxing",		"name":"星星峡",		"lv":1,]),
(["type":3,	"id":"/d/huizhu/caoyuan",		"name":"草原",		"lv":1,]),
(["type":3,	"id":"/d/huizhu/buluo1",		"name":"回族部落",		"lv":1,]),
(["type":3,	"id":"/d/jindezheng/zuanjiao",	"name":"砖窑",		"lv":2,]),
(["type":3,	"id":"/d/jindezheng/peifang",	"name":"工房",		"lv":2,]),
(["type":3,	"id":"/d/jindezheng/gudong-shop",	"name":"藏珍阁",		"lv":2,]),
(["type":3,	"id":"/d/jindezheng/jindezhen",	"name":"景德镇",		"lv":2,]),
(["type":3,	"id":"/d/jinling/gengwu",		"name":"更屋",		"lv":1,]),
(["type":3,	"id":"/d/jinling/ke",		"name":"双龙客栈",		"lv":1,]),
(["type":3,	"id":"/d/jinling/shanglin",	"name":"上林苑",		"lv":1,]),
(["type":3,	"id":"/d/jinling/ziyunlou",	"name":"紫云楼",		"lv":1,]),
(["type":3,	"id":"/d/jinling/chouduan",	"name":"万福绸庄",		"lv":1,]),
(["type":3,	"id":"/d/jinling/fengyage",	"name":"风雅阁",		"lv":1,]),
(["type":3,	"id":"/d/kaifeng/fuwangmiao",	"name":"禹王庙",		"lv":2,]),
(["type":3,	"id":"/d/kaifeng/fanta",		"name":"繁塔",		"lv":2,]),
(["type":3,	"id":"/d/kaifeng/fenjiao",		"name":"粪窖",		"lv":2,]),
(["type":3,	"id":"/d/kaifeng/guandi",		"name":"关帝庙",		"lv":2,]),
(["type":3,	"id":"/d/kaifeng/jieying",		"name":"接引佛殿",		"lv":2,]),
(["type":3,	"id":"/d/kaifeng/fangsheng",	"name":"放生池",		"lv":2,]),
(["type":3,	"id":"/d/kaifeng/daoxiang",	"name":"稻香居",		"lv":2,]),
(["type":3,	"id":"/d/lingjiu/yan",		"name":"失足岩",		"lv":1,]),
(["type":3,	"id":"/d/meizhuang/danqingju",	"name":"丹青生居",		"lv":1,]),
(["type":3,	"id":"/d/meizhuang/tubiwengju",	"name":"秃笔翁居",		"lv":1,]),
(["type":3,	"id":"/d/meizhuang/yuedongmen",	"name":"月洞门",		"lv":1,]),
(["type":3,	"id":"/d/quanzhen/fu-damen",	"name":"候府",		"lv":2,]),
(["type":3,	"id":"/d/quanzhen/xiaomiao",	"name":"土地庙",		"lv":2,]),
(["type":3,	"id":"/d/quanzhen/cuipingfeng",	"name":"翠屏峰顶",		"lv":2,]),
(["type":3,	"id":"/d/sandboy/ground",		"name":"晒谷场",		"lv":1,]),
(["type":3,	"id":"/d/sandboy/pomiao",		"name":"破观音庙",		"lv":1,]),
(["type":3,	"id":"/d/sandboy/zhulin5",		"name":"翠微亭",		"lv":1,]),
(["type":3,	"id":"/d/sandboy/zizhuan",		"name":"紫竹庵",		"lv":1,]),
(["type":3,	"id":"/d/sandboy/reed",		"name":"芦苇荡",		"lv":1,]),
(["type":3,	"id":"/d/sandboy/pigroom",		"name":"猪圈",		"lv":1,]),
(["type":3,	"id":"/d/suzhou/baigongti",	"name":"白公堤",		"lv":1,]),
(["type":3,	"id":"/d/suzhou/datang",		"name":"苏州府大堂",	"lv":1,]),
(["type":3,	"id":"/d/wudang/xuanwumen",	"name":"太子坡",		"lv":2,]),
(["type":3,	"id":"/d/yangzhou/24qiao",		"name":"二十四桥",		"lv":1,]),
(["type":3,	"id":"/d/yangzhou/xilingta",	"name":"栖林塔",		"lv":1,]),
(["type":3,	"id":"/d/yangzhou/xiangzhai",	"name":"竹叶香斋",		"lv":1,]),
(["type":3,	"id":"/d/yanjing/fandian",		"name":"太白酒楼",		"lv":1,]),

});

mapping *renwu2=({
([	"type":1,	"id":"playboy",	"name":"花花公子",	"lv":2,	]),
([	"type":1,	"id":"sanzei tou",	"name":"山贼头",	"lv":2,	]),
([	"type":1,	"id":"snaker",	"name":"舞蛇人",	"lv":2,	]),
([	"type":1,	"id":"trainer",	"name":"教练",	"lv":3,	]),
([	"type":1,	"id":"qing",		"name":"小青",	"lv":3,	]),
([	"type":1,	"id":"li",		"name":"李教头",	"lv":5,	]),
([	"type":1,	"id":"dao ke",	"name":"刀客",	"lv":1,	]),
([	"type":1,	"id":"jian ke",	"name":"剑客",	"lv":1,	]),
([	"type":1,	"id":"yan liu",	"name":"燕六",	"lv":2,	]),
([	"type":1,	"id":"gongzi",	"name":"贵公子",	"lv":2,	]),
([	"type":1,	"id":"laohu",		"name":"老虎",	"lv":5,	]),
([	"type":1,	"id":"shan yang",	"name":"山羊",	"lv":3,	]),
([	"type":1,	"id":"shui niu",	"name":"水牛",	"lv":2,	]),
([	"type":1,	"id":"jianghu yiren","name":"江湖艺人",	"lv":2,	]),
([	"type":1,	"id":"dizi",		"name":"成德殿殿下弟子","lv":5,	]),
([	"type":1,	"id":"heiyi ren",	"name":"黑衣人",	"lv":4,	]),
([	"type":1,	"id":"snake",		"name":"黑冠巨蟒",	"lv":5,	]),
([	"type":1,	"id":"yang lianting","name":"杨莲亭",	"lv":6,	]),
([	"type":1,	"id":"chushi",	"name":"胖厨师",	"lv":3,	]),
([	"type":1,	"id":"junshi",	"name":"骁骑营军士","lv":3,	]),
([	"type":1,	"id":"shang ren",	"name":"神照上人",	"lv":4,	]),
([	"type":1,	"id":"junshi",	"name":"前锋营军士","lv":4,	]),
([	"type":1,	"id":"kang qingwang","name":"康亲王",	"lv":2,	]),
([	"type":1,	"id":"yafu",		"name":"哑妇",	"lv":2,	]),
([	"type":1,	"id":"hua guwen",	"name":"华孤坟",	"lv":3,	]),
([	"type":1,	"id":"sha qiandeng","name":"沙千灯",	"lv":2,	]),
([	"type":1,	"id":"tang fang",	"name":"唐方",	"lv":1,	]),
([	"type":1,	"id":"yan guigui",	"name":"阎鬼鬼",	"lv":2,	]),
([	"type":1,	"id":"fu tianyi",	"name":"傅天义",	"lv":2,	]),
([	"type":1,	"id":"zuo changsheng","name":"左常生",	"lv":4,	]),
([	"type":1,	"id":"xin huqiu",	"name":"辛虎丘",	"lv":3,	]),
([	"type":1,	"id":"lin pingzhi",	"name":"林平之",	"lv":4,	]),
([	"type":1,	"id":"lao denuo",	"name":"劳德诺",	"lv":4,	]),
([	"type":1,	"id":"ren fanzi",	"name":"人贩子",	"lv":5,	]),
([	"type":1,	"id":"woman",		"name":"青衣妇人",	"lv":5,	]),
([	"type":1,	"id":"zhuangding",	"name":"庄丁",	"lv":4,	]),
([	"type":1,	"id":"hou yuanwai",	"name":"侯员外",	"lv":1,	]),
([	"type":1,	"id":"gai yiming",	"name":"盖一鸣",	"lv":1,	]),
([	"type":1,	"id":"hua jianying","name":"花剑影",	"lv":1,	]),
([	"type":1,	"id":"chang changfeng","name":"常长风",	"lv":2,	]),
([	"type":1,	"id":"cui baiquan",	"name":"崔百泉",	"lv":2,	]),
([	"type":1,	"id":"jieba",		"name":"街霸",	"lv":1,	]),
([	"type":1,	"id":"shen laocai",	"name":"沈老财",	"lv":4,	]),
([	"type":1,	"id":"wang furen",	"name":"王夫人",	"lv":4,	]),
([	"type":1,	"id":"sima lin",	"name":"司马林",	"lv":3,	]),
([	"type":1,	"id":"yao bodang",	"name":"姚伯当",	"lv":4,	]),
([	"type":1,	"id":"zai ding",	"name":"寨丁",	"lv":2,	]),
([	"type":1,	"id":"zhu baokun",	"name":"诸保昆",	"lv":4,	]),
([	"type":1,	"id":"zhuang ding",	"name":"庄丁",	"lv":4,	]),
([	"type":1,	"id":"zhuang han",	"name":"壮汉",	"lv":4,	]),
([	"type":1,	"id":"makepilo",	"name":"马可皮罗",	"lv":4,	]),
([	"type":1,	"id":"baobiao",	"name":"洋保镖",	"lv":2,	]),
([	"type":1,	"id":"wan daping",	"name":"万大平",	"lv":4,	]),
([	"type":1,	"id":"di xiu",	"name":"狄修",	"lv":5,	]),
([	"type":1,	"id":"shi dengda",	"name":"史登达",	"lv":5,	]),
([	"type":1,	"id":"tufei tou",	"name":"土匪头",	"lv":1,	]),
([	"type":1,	"id":"jianchu daoren","name":"建除道人","lv":5,	]),
([	"type":1,	"id":"hufa",		"name":"护法",	"lv":5,	]),
([	"type":1,	"id":"fisherman",	"name":"渔夫",	"lv":2,	]),
([	"type":1,	"id":"liusan",	"name":"刘三爷",	"lv":5,	]),
([	"type":1,	"id":"baiyi ren",	"name":"白衣人",	"lv":4,	]),
([	"type":1,	"id":"shou wei",	"name":"守卫",	"lv":3,	]),
([	"type":1,	"id":"zhu youmu",	"name":"朱由穆",	"lv":1,	]),
([	"type":1,	"id":"likui",		"name":"李逵",	"lv":4,	]),
([	"type":1,	"id":"weichunhua",	"name":"韦春花",	"lv":2,	]),
([	"type":1,	"id":"kan shou",	"name":"王府看守",	"lv":1,	]),
([	"type":1,	"id":"hou tonghai",	"name":"侯通海",	"lv":4,	]),
([	"type":1,	"id":"lingzhi shangren","name":"灵智上人","lv":4,	]),
([	"type":1,	"id":"qin bing",	"name":"王府亲兵",	"lv":3,	]),
([	"type":1,	"id":"sha tongtian","name":"沙通天",	"lv":4,	]),
([	"type":1,	"id":"wangye",	"name":"完颜洪烈",	"lv":4,	]),
([	"type":1,	"id":"wanyan kang",	"name":"完颜康",	"lv":6,	]),
([	"type":1,	"id":"xiao toumu",	"name":"野羊寨小头目","lv":4,	]),
([	"type":1,	"id":"zaiding",	"name":"野羊寨寨丁","lv":3,	]),

([	"type":1,	"id":"wu jiang",	"name":"武将",	"lv":3,	]),
([	"type":1,	"id":"yuan chanshi","name":"圆觉禅师",	"lv":1,	]),
([	"type":1,	"id":"seng ren",	"name":"游方和尚",	"lv":1,	]),
([	"type":1,	"id":"wei bing",	"name":"卫兵",	"lv":2,	]),
([	"type":1,	"id":"guan bing",	"name":"官兵",	"lv":1,	]),
([	"type":1,	"id":"shi bing",	"name":"士兵",	"lv":1,	]),
([	"type":1,	"id":"da tusi",	"name":"大土司",	"lv":1,	]),
([	"type":1,	"id":"jianghu yiren","name":"江湖艺人",	"lv":2,	]),
([	"type":1,	"id":"ji si",		"name":"祭司",	"lv":2,	]),
([	"type":1,	"id":"lao jisi",	"name":"老祭司",	"lv":2,	]),
([	"type":1,	"id":"lie ren",	"name":"猎人",	"lv":1,	]),
([	"type":1,	"id":"lie ren",	"name":"台夷猎人",	"lv":1,	]),
([	"type":1,	"id":"po chen",	"name":"破嗔",	"lv":2,	]),
([	"type":1,	"id":"po yi",		"name":"破疑",	"lv":3,	]),
([	"type":1,	"id":"shennong dizi","name":"神农帮弟子","lv":1,	]),
([	"type":1,	"id":"shi cong",	"name":"侍从",	"lv":1,	]),
([	"type":1,	"id":"daizu shouling","name":"傣族首领","lv":2,	]),
([	"type":1,	"id":"wei shi",	"name":"锦衣卫士",	"lv":2,	]),
([	"type":1,	"id":"wei shi",	"name":"素衣卫士",	"lv":1,	]),
([	"type":1,	"id":"wuliang dizi","name":"无量剑弟子","lv":1,	]),
([	"type":1,	"id":"zu touren",	"name":"族头人",	"lv":4,	]),
([	"type":1,	"id":"zu zhang",	"name":"族长",	"lv":2,	]),
([	"type":1,	"id":"chushi",	"name":"胖厨师",	"lv":4,	]),
([	"type":1,	"id":"xuxian",	"name":"许仙",	"lv":6,	]),
([	"type":1,	"id":"bai hanfeng",	"name":"白寒枫",	"lv":4,	]),
([	"type":1,	"id":"kang qingwang","name":"康亲王",	"lv":2,	]),
([	"type":1,	"id":"junshi",	"name":"前锋营军士","lv":4,	]),
([	"type":1,	"id":"shang ren",	"name":"神照上人",	"lv":4,	]),
([	"type":1,	"id":"junshi",	"name":"骁骑营军士","lv":2,	]),
([	"type":1,	"id":"zhang kangnian","name":"张康年",	"lv":5,	]),
([	"type":1,	"id":"zhao qixian",	"name":"赵齐贤",	"lv":5,	]),
([	"type":1,	"id":"kong yangqin","name":"孔扬秦",	"lv":3,	]),
([	"type":1,	"id":"jiang xiuyin","name":"江秀音",	"lv":1,	]),
([	"type":1,	"id":"wen yanyang",	"name":"温艳阳",	"lv":1,	]),
([	"type":1,	"id":"deng diaoliang","name":"登雕梁",	"lv":1,	]),
([	"type":1,	"id":"deng yuhan",	"name":"邓玉函",	"lv":1,	]),
([	"type":1,	"id":"zhang",		"name":"张临意",	"lv":4,	]),
([	"type":1,	"id":"xin huqiu",	"name":"辛虎丘",	"lv":4,	]),
([	"type":1,	"id":"sun huisan",	"name":"孙慧珊",	"lv":3,	]),
([	"type":1,	"id":"xiao xilou",	"name":"萧西楼",	"lv":4,	]),
([	"type":1,	"id":"zhu xiawu",	"name":"朱侠武",	"lv":4,	]),
([	"type":1,	"id":"lu dayou",	"name":"陆大有",	"lv":2,	]),
([	"type":1,	"id":"gao genming",	"name":"高根明",	"lv":2,	]),
([	"type":1,	"id":"liang fa",	"name":"梁发",	"lv":2,	]),
([	"type":1,	"id":"shi daizi",	"name":"施戴子",	"lv":2,	]),
([	"type":1,	"id":"yue lingshan","name":"岳灵珊",	"lv":4,	]),
([	"type":1,	"id":"gong zhu",	"name":"香香公主",	"lv":2,	]),
([	"type":1,	"id":"famu gong",	"name":"伐木工",	"lv":2,	]),
([	"type":1,	"id":"gongren",	"name":"烧窑工",	"lv":2,	]),
([	"type":1,	"id":"chengwei",	"name":"城卫",	"lv":1,	]),
([	"type":1,	"id":"gong zi",	"name":"富家公子",	"lv":4,	]),
([	"type":1,	"id":"seng ren",	"name":"护寺僧人",	"lv":3,	]),
([	"type":1,	"id":"kong",		"name":"孔大官人",	"lv":2,	]),
([	"type":1,	"id":"liu caizhu",	"name":"刘大财主",	"lv":3,	]),
([	"type":1,	"id":"pihuo shang",	"name":"皮货商",	"lv":1,	]),
([	"type":1,	"id":"xiaoshidi",	"name":"小师弟",	"lv":4,	]),
([	"type":1,	"id":"li ping",	"name":"李萍",	"lv":3,	]),
([	"type":1,	"id":"mu min",	"name":"蒙古牧民",	"lv":3,	]),
([	"type":1,	"id":"tong",		"name":"道童",	"lv":1,	]),
([	"type":1,	"id":"li zhichang",	"name":"李志常",	"lv":5,	]),
([	"type":1,	"id":"qi zhicheng",	"name":"祁志诚",	"lv":5,	]),
([	"type":1,	"id":"yin zhiping",	"name":"尹志平",	"lv":5,	]),
([	"type":1,	"id":"zhangjing",	"name":"掌经道长",	"lv":2,	]),
([	"type":1,	"id":"zhangli",	"name":"掌理道长",	"lv":2,	]),
([	"type":1,	"id":"zhangyao",	"name":"掌药道长",	"lv":2,	]),
([	"type":1,	"id":"cha laohan",	"name":"茶老汉",	"lv":1,	]),
([	"type":1,	"id":"sansao",	"name":"张山嫂",	"lv":1,	]),
([	"type":1,	"id":"zhang san",	"name":"张山",	"lv":2,	]),
([	"type":1,	"id":"a bi",		"name":"阿碧",	"lv":2,	]),
([	"type":1,	"id":"baobiao",	"name":"洋保镖",	"lv":2,	]),
([	"type":1,	"id":"makepilo",	"name":"马可皮罗",	"lv":4,	]),
([	"type":1,	"id":"lao furen",	"name":"老夫人",	"lv":2,	]),
([	"type":1,	"id":"a zhu",		"name":"阿朱",	"lv":3,	]),
([	"type":1,	"id":"chi baicheng","name":"迟百城",	"lv":4,	]),
([	"type":1,	"id":"guxu daozhang","name":"谷虚道长",	"lv":3,	]),
([	"type":1,	"id":"song qingshu","name":"宋青书",	"lv":4,	]),
([	"type":1,	"id":"saodi seng",	"name":"扫地僧",	"lv":4,	]),
([	"type":1,	"id":"huta seng",	"name":"护塔僧",	"lv":4,	]),
([	"type":1,	"id":"baiyi ren",	"name":"白衣人",	"lv":4,	]),
([	"type":1,	"id":"guo xiaotian","name":"郭啸天",	"lv":2,	]),
([	"type":1,	"id":"mingxin",	"name":"明性",	"lv":4,	]),
([	"type":1,	"id":"shou wei",	"name":"守卫",	"lv":4,	]),
([	"type":1,	"id":"xin ji",	"name":"性寂",	"lv":2,	]),
([	"type":1,	"id":"xie ying",	"name":"谢璎",	"lv":4,	]),
([	"type":1,	"id":"bilian",	"name":"碧涟",	"lv":4,	]),
([	"type":1,	"id":"yang tiexin",	"name":"杨铁心",	"lv":3,	]),
([	"type":1,	"id":"bai guishou",	"name":"白龟寿",	"lv":2,	]),
([	"type":1,	"id":"chang jinpeng","name":"常金鹏",	"lv":3,	]),
([	"type":1,	"id":"cheng chaofeng","name":"程嘲风",	"lv":2,	]),
([	"type":1,	"id":"feng gongying","name":"封弓影",	"lv":3,	]),
([	"type":1,	"id":"gao shanwang","name":"高山王",	"lv":2,	]),
([	"type":1,	"id":"li tianyuan",	"name":"李天垣",	"lv":4,	]),
([	"type":1,	"id":"da han",	"name":"明教大汉",	"lv":1,	]),
([	"type":1,	"id":"peng yingyu",	"name":"彭莹玉",	"lv":4,	]),
([	"type":1,	"id":"shuo bude",	"name":"说不得",	"lv":4,	]),
([	"type":1,	"id":"tang yang",	"name":"唐洋",	"lv":4,	]),
([	"type":1,	"id":"tuoba",		"name":"拓跋",	"lv":3,	]),
([	"type":1,	"id":"xin ran",	"name":"辛然",	"lv":4,	]),
([	"type":1,	"id":"yan yuan",	"name":"严垣",	"lv":2,	]),
([	"type":1,	"id":"zhuang zheng","name":"庄铮",	"lv":3,	]),
([	"type":1,	"id":"zhou dian",	"name":"周颠",	"lv":4,	]),
([	"type":1,	"id":"zhang zhong",	"name":"张中",	"lv":4,	]),
([	"type":1,	"id":"yin wushou",	"name":"殷无寿",	"lv":4,	]),
([	"type":1,	"id":"yin wulu",	"name":"殷无禄",	"lv":4,	]),
([	"type":1,	"id":"yin wufu",	"name":"殷无福",	"lv":4,	]),
([	"type":1,	"id":"guan anji",	"name":"关安基",	"lv":3,	]),
([	"type":1,	"id":"li lishi",	"name":"李力世",	"lv":2,	]),
([	"type":1,	"id":"qian laoben",	"name":"钱老本",	"lv":4,	]),


([	"type":2,	"id":"shedan gao",		"name":"蛇胆膏",		"lv":2,]),
([	"type":2,	"id":"wuliangye",		"name":"五粮液",		"lv":3,]),
([	"type":2,	"id":"cha hua",		"name":HIY"落第秀才"NOR,	"lv":1,]),
([	"type":2,	"id":"cha hua",		"name":HIB"眼"HIW"儿媚"NOR,"lv":1,]),
([	"type":2,	"id":"cha hua",	"name":HIR"红妆"HIW"素裹"NOR,	"lv":1,]),
([	"type":2,"id":"cha hua","name":HIW"抓破"HIG"美"NOR"人"HIR"脸"NOR,	"lv":1,]),
([	"type":2,	"id":"cha hua",	"name":HIW"倚"HIG"栏"HIR"娇"NOR,	"lv":1,]),
([	"type":2,	"id":"cha hua",		"name":HIR"十八学士"NOR,	"lv":1,]),
([	"type":2,	"id":"cha hua",		"name":HIG"十三太保"NOR,	"lv":1,]),
([	"type":2,	"id":"cha hua",		"name":HIB"八仙过海"NOR,	"lv":1,]),
([	"type":2,	"id":"cha hua",		"name":HIR"七仙女"NOR,	"lv":1,]),
([	"type":2,	"id":"cha hua","name":MAG"风"WHT"尘三"HIR"侠"NOR,	"lv":1,]),
([	"type":2,	"id":"cha hua",		"name":HIR"二"WHT"乔"NOR,	"lv":1,]),
([	"type":2,	"id":"cha hua",		"name":HIG"八宝妆"NOR,	"lv":1,]),
([	"type":2,	"id":"cha hua",		"name":HIW"满月"NOR,	"lv":1,]),
([	"type":2,	"id":"cha hua",		"name":HIR"山茶花"NOR,	"lv":1,]),
([	"type":2,	"id":"dou peng",		"name":"斗篷",		"lv":2,]),
([	"type":2,	"id":"junfu",			"name":"锦衣军服",		"lv":3,]),
([	"type":2,	"id":"junfu",			"name":"黄衣军服",		"lv":2,]),
([	"type":2,	"id":"fangsha ji",		"name":"纺纱机",		"lv":1,]),
([	"type":2,	"id":"li",			"name":"大理雪梨",		"lv":1,]),
([	"type":2,	"id":"duan qun",		"name":"摆夷短裙",		"lv":1,]),
([	"type":2,	"id":"duan qun",		"name":"台夷短裙",		"lv":1,]),
([	"type":2,	"id":"tong qun",		"name":"筒裙",		"lv":1,]),
([	"type":2,	"id":"tou jin",		"name":"台夷头巾",		"lv":1,]),
([	"type":2,	"id":"chang qun",		"name":"乌夷长裙",		"lv":1,]),
([	"type":2,	"id":"da hui",		"name":"乌夷大麾",		"lv":2,]),
([	"type":2,	"id":"qingshui doufu",	"name":HIW"清水豆腐"NOR,	"lv":1,]),
([	"type":2,	"id":"shuijing doufu",	"name":HIW"水晶豆腐"NOR,	"lv":1,]),
([	"type":2,	"id":"wuxiang huasheng",	"name":HIY"五香花生米"NOR,	"lv":1,]),
([	"type":2,	"id":"jiaoyan paigu",	"name":HIR"椒盐排骨"NOR,	"lv":1,]),
([	"type":2,	"id":"pangxie",		"name":HIC"清蒸螃蟹"NOR,	"lv":1,]),
([	"type":2,	"id":"shi gu",		"name":"尸骨",		"lv":1,]),
([	"type":2,	"id":"fuling",		"name":YEL"茯苓"NOR,	"lv":2,]),
([	"type":2,	"id":"moyao",			"name":HIW"没药"NOR,	"lv":2,]),
([	"type":2,	"id":"tianqi",		"name":HIY"田七"NOR,	"lv":2,]),
([	"type":2,	"id":"xiongdan",		"name":HIR"熊胆"NOR,	"lv":2,]),
([	"type":2,	"id":"xuejie",		"name":RED"血竭"NOR,	"lv":2,]),
([	"type":2,	"id":"guiling gao",		"name":HIW"龟苓膏"NOR,	"lv":2,]),
([	"type":2,	"id":"bingfu",		"name":"兵服",		"lv":1,]),
([	"type":2,	"id":"duangua",		"name":"小短褂",		"lv":1,]),
([	"type":2,	"id":"xiang",			"name":"地藏菩萨像",	"lv":3,]),
([	"type":2,	"id":"xiang",			"name":"观音菩萨像",	"lv":2,]),
([	"type":2,	"id":"xiang",			"name":"金塔像",		"lv":3,]),
([	"type":2,	"id":"jing",			"name":"妙法莲华经",	"lv":2,]),
([	"type":2,	"id":"nidao",			"name":"泥刀",		"lv":3,]),
([	"type":2,	"id":"xiang",			"name":"释迦牟尼佛像",	"lv":2,]),
([	"type":2,	"id":"zhuding",		"name":"竹钉",		"lv":1,]),
([	"type":2,	"id":"bishou",		"name":"匕首",		"lv":1,]),
([	"type":2,	"id":"tie suanpan",		"name":"铁算盘",		"lv":1,]),
([	"type":2,	"id":"yinyang-sword",	"name":"阴阳剑",		"lv":3,]),
([	"type":2,	"id":"yin zhen",		"name":"银针",		"lv":2,]),
([	"type":2,	"id":"gujian",		"name":"古剑",		"lv":2,]),
([	"type":2,	"id":"leigong hong",	"name":"雷公轰",		"lv":3,]),
([	"type":2,	"id":"shanzi",		"name":"扇子",		"lv":2,]),
([	"type":2,	"id":"ban fu",		"name":"板斧",		"lv":1,]),
([	"type":2,	"id":"da dao",		"name":"大刀",		"lv":2,]),
([	"type":2,	"id":"she pi",		"name":"蛇皮",		"lv":2,]),
([	"type":2,	"id":"junfu",			"name":"军服",		"lv":2,]),
([	"type":2,	"id":"duijin guazi",	"name":"对衿褂子",		"lv":1,]),
([	"type":2,	"id":"kan dao",		"name":"砍刀",		"lv":1,]),
([	"type":2,	"id":"ken ao",		"name":"窄裉袄",		"lv":1,]),
([	"type":2,	"id":"shell lace",		"name":"贝壳项链",		"lv":2,]),
([	"type":2,	"id":"man dao",		"name":"蛮刀",		"lv":1,]),
([	"type":2,	"id":"mao tan",		"name":"毛毯",		"lv":1,]),
([	"type":2,	"id":"xiangbian qun",	"name":"白纱挑线镶边裙",	"lv":1,]),
([	"type":2,	"id":"da fu",			"name":"大斧",		"lv":1,]),
([	"type":2,	"id":"niuer dao",		"name":"牛耳尖刀",		"lv":1,]),
([	"type":2,	"id":"bigaxe",		"name":"大板斧",		"lv":1,]),
([	"type":2,	"id":"diao pi",		"name":"貂皮大衣",		"lv":2,]),
([	"type":2,	"id":"xuanwei huotui",	"name":HIR"宣威火腿"NOR,	"lv":1,]),
([	"type":2,	"id":"ye er ba",		"name":HIG"叶儿粑"NOR,	"lv":1,]),
([	"type":2,	"id":"fish",			"name":YEL"宋嫂鱼"NOR,	"lv":1,]),
([	"type":2,	"id":"dachengjing",		"name":"大乘经",		"lv":1,]),
([	"type":2,	"id":"daodejing",		"name":"道德经",		"lv":1,]),
([	"type":2,	"id":"taihu tu",		"name":"太湖旅游图",	"lv":2,]),
([	"type":2,	"id":"hat",			"name":"银色皮帽",		"lv":1,]),
([	"type":2,	"id":"jin duan",		"name":"锦缎",		"lv":1,]),
([	"type":2,	"id":"laoshan shen",	"name":"老山参",		"lv":2,]),
([	"type":2,	"id":"mudi",			"name":"牧笛",		"lv":1,]),
([	"type":2,	"id":"muyu",			"name":"木鱼",		"lv":1,]),
([	"type":2,	"id":"hua ban",		"name":"花瓣",		"lv":2,]),
([	"type":2,	"id":"shanzi",		"name":"檀香扇",		"lv":1,]),
([	"type":2,	"id":"gao",			"name":"冰雪翡翠糕",	"lv":2,]),
([	"type":2,	"id":"canhezhi",		"name":"参合指要诀",	"lv":3,]),
([	"type":2,	"id":"tanyunshou",		"name":"探云手要诀",	"lv":2,]),
([	"type":2,	"id":"tuling fu",		"name":"土灵符",		"lv":1,]),
([	"type":2,	"id":"golden ring",		"name":"金戒指",		"lv":2,]),
([	"type":2,	"id":"xifu",			"name":"西服",		"lv":3,]),
([	"type":2,	"id":"yan",			"name":"香烟",		"lv":2,]),
([	"type":2,	"id":"zuanshijiezhi",	"name":"钻石戒指",		"lv":2,]),
([	"type":2,	"id":"jian pu",		"name":"天羽奇剑剑谱",	"lv":3,]),
([	"type":2,	"id":"baiyun wan",		"name":"白云熊胆丸",	"lv":3,]),
([	"type":2,	"id":"lingshen san",	"name":"灵神散",		"lv":1,]),
([	"type":2,	"id":"liushen wan",		"name":"六神丸",		"lv":1,]),
([	"type":2,	"id":"nianhua san",		"name":"拈花散",		"lv":1,]),
([	"type":2,	"id":"sanqing dan",		"name":"三清丹",		"lv":1,]),
([	"type":2,	"id":"xiaojing dan",	"name":"小精丹",		"lv":1,]),
([	"type":2,	"id":"xuqi wan",		"name":"虚气丸",		"lv":1,]),
([	"type":2,	"id":"zhengqi wan",		"name":"正气丸",		"lv":1,]),

(["type":3,	"id":"/d/baituo/midao",		"name":"白驼山密道",	"lv":2,]),
(["type":3,	"id":"/d/baituo/cave",		"name":"白驼山岩洞",	"lv":2,]),
(["type":3,	"id":"/d/baituo/cedong",		"n":"土灵符",		"lv":1,]),
([	"type":2,	"id":"golden ring",		"name":"金戒指",		"lv":2,]),
([	"type":2,	"id":"xifu",			"name":"西服",		"lv":3,]),
([	"type":2,	"id":"yan",			"name":"香烟",		"lv":2,]),
([	"type":2,	"id":"zuanshijiezhi",	"name":"钻石戒指",		"lv":2,]),
([	"type":2,	"id":"jian pu",		"name":"天羽奇剑剑谱",	"lv":3,]),
([	"type":2,	"id":"baiyun wan",		"name":"白云熊胆丸",	"lv":3,]),
([	"type":2,	"id":"lingshen san",	"name":"灵神散",		"lv":1,]),
([	"type":2,	"id":"liushen wan",		"name":"六神丸",		"lv":1,]),
([	"type":2,	"id":"nianhua san",		"name":"拈花散",		"lv":1,]),
([	"type":2,	"id":"sanqing dan",		"name":"三清丹",		"lv":1,]),
([	"type":2,	"id":"xiaojing dan",	"name":"小精丹",		"lv":1,]),
([	"type":2,	"id":"xuqi wan",		"name":"虚气丸",		"lv":1,]),
([	"type":2,	"id":"zhengqi wan",		"name":"正气丸",		"lv":1,]),

(["type":3,	"id":"/d/baituo/midao",		"name":"白驼山密道",	"lv":2,]),
(["type":3,	"id":"/d/baituo/cave",		"name":"白驼山岩洞",	"lv":2,]),
(["type":3,	"id":"/d/baituo/cedong",		"name":"侧洞",		"lv":2,]),
(["type":3,	"id":"/d/chengdu/fengyuting",	"name":"风雨亭",		"lv":1,]),
(["type":3,	"id":"/d/chengdu/liangting",	"name":"凉亭",		"lv":1,]),
(["type":3,	"id":"/d/chengdu/xuetao",		"name":"薛涛井",		"lv":1,]),
(["type":3,	"id":"/d/chengdu/wangjianglou1",	"name":"望江楼",		"lv":1,]),
(["type":3,	"id":"/d/tianlongsi/tading",	"name":"舍利塔塔顶",	"lv":2,]),
(["type":3,	"id":"/d/hangzhou/louwai",		"name":"楼外楼",		"lv":1,]),
(["type":3,	"id":"/d/hangzhou/wuyuan",		"name":"吴园",		"lv":1,]),
(["type":3,	"id":"/d/hangzhou/duanqiao",	"name":"断桥残雪",		"lv":1,]),
([	"type":2,	"id":"xiaojing dan",	"name":"小精丹",		"lv":1,]),
([	"type":2,	"id":"xuqi wan",		"name":"虚气丸",		"lv":1,]),
([	"type":2,	"id":"zhengqi wan",		"name":"正气丸",		"lv":1,]),

(["type":3,	"id":"/d/baituo/midao",		"name":"白驼山密道",	"lv":2,]),
(["type":3,	"id":"/d/baituo/cave",		"name":"白驼山岩洞",	"lv":2,]),
(["type":3,	"id":"/d/baituo/cedong",		"name":"侧洞",		"lv":2,]),
(["type":3,	"id":"/d/chengdu/fengyuting",	"name":"风雨亭",		"lv":1,]),
(["type":3,	"id":"/d/chengdu/liangting",	"name":"凉亭",		"lv":1,]),
(["type":3,	"id":"/d/chengdu/xuetao",		"name":"薛涛井",		"lv":1,]),
(["type":3,	"id":"/d/chengdu/wangjianglou1",	"name":"望江楼",		"lv":1,]),
(["type":3,	"id":"/d/tianlongsi/tading",	"name":"舍利塔塔顶",	"lv":2,]),
(["type":3,	"id":"/d/hangzhou/louwai",		"name":"楼外楼",		"lv":1,]),
(["type":3,	"id":"/d/hangzhou/wuyuan",		"name":"吴园",		"lv":1,]),
(["type":3,	"id":"/d/hangzhou/duanqiao",	"name":"断桥残雪",		"lv":1,]),
(["type":3,     "type":2,      "id":"sanqing dan",             "name":"三清丹",                "lv":1,]),
([	"type":2,	"id":"xiaojing dan",	"name":"小精丹",		"lv":1,]),
([	"type":2,	"id":"xuqi wan",		"name":"虚气丸",		"lv":1,]),
([	"type":2,	"id":"zhengqi wan",		"name":"正气丸",		"lv":1,]),

(["type":3,	"id":"/d/baituo/midao",		"name":"白驼山密道",	"lv":2,]),
(["type":3,	"id":"/d/baituo/cave",		"name":"白驼山岩洞",	"lv":2,]),
(["type":3,	"id":"/d/baituo/cedong",		"name":"侧洞",		"lv":2,]),
(["type":3,	"id":"/d/chengdu/fengyuting",	"name":"风雨亭",		"lv":1,]),
(["type":3,	"id":"/d/chengdu/liangting",	"name":"凉亭",		"lv":1,]),
(["type":3,	"id":"/d/chengdu/xuetao",		"name":"薛涛井",		"lv":1,]),
(["type":3,	"id":"/d/chengdu/wangjianglou1",	"name":"望江楼",		"lv":1,]),
(["type":3,	"id":"/d/tianlongsi/tading",	"name":"舍利塔塔顶",	"lv":2,]),
(["type":3,	"id":"/d/hangzhou/louwai",		"name":"楼外楼",		"lv":1,]),
(["type":3,	"id":"/d/hangzhou/wuyuan",		"name":"吴园",		"lv":1,]),
(["type":3,	"id":"/d/hangzhou/duanqiao",	"name":"断桥残雪",		"lv":1,]),
(["type":3,	"id":"/d/hangzhou/tanei",		"name":"雷峰塔内",		"lv":1,]),
(["type":3,	"id":"/d/hangzhou/jingci",		"name":"净慈寺",		"lv":1,]),
(["type":3,	"id":"/d/heimuya/shimen",		"name":"石门",		"lv":1,]),
(["type":3,	"id":"/d/heimuya/shenggu",		"name":"圣姑堂",		"lv":2,]),
(["type":3,	"id":"/d/heimuya/tian1",		"name":"天香堂大厅",	"lv":1,]),
(["type":3,	"id":"/d/heimuya/fen0",		"name":"风雷堂大厅",	"lv":1,]),
(["type":3,	"id":"/d/heimuya/baihutang",	"name":"白虎堂大厅",	"lv":3,]),
(["type":3,	"id":"/d/heimuya/qing",		"name":"青龙堂大厅",	"lv":1,]),
(["type":3,	"id":"/d/huanggon/dawu",		"name":"海大富居处",	"lv":1,]),
(["type":3,	"id":"/d/huanggon/junjichu",	"name":"军机处",		"lv":1,]),
(["type":3,	"id":"/d/huanggon/wumen",		"name":"午门",		"lv":1,]),
(["type":3,	"id":"/d/huanggon/ciqinggon",	"name":"太后寝宫",		"lv":1,]),
(["type":3,	"id":"/d/huanhua/whitefeng",	"name":"白云峰",		"lv":2,]),
(["type":3,	"id":"/d/huanhua/lshanguan",	"name":"娄山关",		"lv":1,]),
(["type":3,	"id":"/d/huanhua/hxianting",	"name":"会仙亭",		"lv":2,]),
(["type":3,	"id":"/d/huanhua/jxiulou",		"name":"甲秀楼",		"lv":1,]),
(["type":3,	"id":"/d/huashan/siguoya",		"name":"思过崖",		"lv":2,]),
(["type":3,	"id":"/d/huashan/ziqitai",		"name":"紫气台",		"lv":1,]),
(["type":3,	"id":"/d/huashan/chaoyang",	"name":"朝阳峰",		"lv":2,]),
(["type":3,	"id":"/d/huashan/shufang",		"name":"华山书房",		"lv":1,]),
(["type":3,	"id":"/d/huashan/jiashan",		"name":"假山小池",		"lv":2,]),
(["type":3,	"id":"/d/huashan/xuanya",		"name":"悬崖",		"lv":1,]),
(["type":3,	"id":"/d/huashan/qunxianguan",	"name":"群仙观",		"lv":2,]),
(["type":3,	"id":"/d/huashan/lianhua",		"name":"莲花峰",		"lv":1,]),
(["type":3,	"id":"/d/huashan/chengxiang",	"name":"沉香劈山处",	"lv":2,]),
(["type":3,	"id":"/d/huashan/yunu",		"name":"玉女峰",		"lv":1,]),
(["type":3,	"id":"/d/huashan/xiuxishi",	"name":"华山小筑",		"lv":1,]),
(["type":3,	"id":"/d/huashan/luoyan",		"name":"落雁峰",		"lv":3,]),
(["type":3,	"id":"/d/huizhu/jiayuguan",	"name":"嘉峪关",		"lv":1,]),
(["type":3,	"id":"/d/huizhu/xingxing",		"name":"星星峡",		"lv":1,]),
(["type":3,	"id":"/d/huizhu/caoyuan",		"name":"草原",		"lv":1,]),
(["type":3,	"id":"/d/huizhu/buluo1",		"name":"回族部落",		"lv":2,]),
(["type":3,	"id":"/d/menggu/yinzhang",		"name":"铁木真营帐",	"lv":2,]),
(["type":3,	"id":"/d/menggu/qingwei",		"name":"亲卫营",		"lv":1,]),
(["type":3,	"id":"/d/menggu/menggubao",	"name":"蒙古包",		"lv":2,]),
(["type":3,	"id":"/d/menggu/caoyuan",		"name":"蒙古草原",		"lv":1,]),
(["type":3,	"id":"/d/robber/tomb1",		"name":"坟场",		"lv":1,]),
(["type":3,	"id":"/d/robber/tree5",		"name":"松柏密林",		"lv":2,]),
(["type":3,	"id":"/d/robber/tearoom",		"name":"茶寮",		"lv":1,]),
(["type":3,	"id":"/d/quanzhen/banshanting",	"name":"半山亭",		"lv":2,]),
(["type":3,	"id":"/d/quanzhen/yuzhengong",	"name":"遇真宫",		"lv":1,]),
(["type":3,	"id":"/d/quanzhen/yuanshidian",	"name":"元始殿",		"lv":2,]),
(["type":3,	"id":"/d/songshan/taishique",	"name":"太室阙",		"lv":1,]),
(["type":3,	"id":"/d/songshan/tianzhongge",	"name":"天中阁",		"lv":2,]),
(["type":3,	"id":"/d/songshan/qimuque",	"name":"启母阙",		"lv":1,]),
(["type":3,	"id":"/d/songshan/fawangsi",	"name":"法王寺",		"lv":2,]),
(["type":3,	"id":"/d/songshan/chaotian",	"name":"朝天门",		"lv":1,]),
(["type":3,	"id":"/d/songshan/chanyuan",	"name":"峻极禅院",		"lv":2,]),
(["type":3,	"id":"/d/songshan/luyanpubu",	"name":"芦岩瀑布",		"lv":1,]),
(["type":3,	"id":"/d/suzhou/datang",		"name":"苏州府大堂",	"lv":1,]),
(["type":3,	"id":"/d/taishan/yitian",		"name":"一天门",		"lv":2,]),
(["type":3,	"id":"/d/taishan/shengxian",	"name":"升仙坊",		"lv":2,]),
(["type":3,	"id":"/d/taishan/shixin",		"name":"试心石",		"lv":2,]),
(["type":3,	"id":"/d/taishan/yuhuang",		"name":"玉皇顶",		"lv":2,]),
(["type":3,	"id":"/d/taishan/beitian",		"name":"北天门",		"lv":2,]),
(["type":3,	"id":"/d/yandang/xiaolongq",	"name":"小龙湫",		"lv":1,]),
(["type":3,	"id":"/d/yandang/luoyan27",	"name":"天一阁",		"lv":2,]),
(["type":3,	"id":"/d/yandang/luoyan33",	"name":"中折瀑",		"lv":1,]),
(["type":3,	"id":"/d/yandang/luoyan38",	"name":"喷泉",		"lv":2,]),
(["type":3,	"id":"/d/yandang/luoyan37",	"name":"西花厅",		"lv":1,]),
(["type":3,	"id":"/d/yandang/luoyan25",	"name":"冷雁池塘",		"lv":2,]),
(["type":3,	"id":"/d/yandang/shandong6",	"name":"玲珑洞",		"lv":1,]),
(["type":3,	"id":"/d/yandang/shandong4",	"name":"隐虎洞",		"lv":2,]),
(["type":3,	"id":"/d/yandang/guanyin",		"name":"观音洞",		"lv":1,]),
(["type":3,	"id":"/d/yandang/xiyaotai",	"name":"西瑶台",		"lv":2,]),
(["type":3,	"id":"/d/zhongzhou/fuwu",		"name":"休闲中心大堂",	"lv":2,]),
(["type":3,	"id":"/d/zhongzhou/yanguan",	"name":"鸦片馆",		"lv":2,]),
(["type":3,	"id":"/d/zhongzhou/liwu",		"name":"漕帮里屋",		"lv":2,]),
(["type":3,	"id":"/d/sandboy/intree",		"name":"大榕树上",		"lv":2,]),

});

mapping *renwu3=({
([	"type":1,	"id":"li",		"name":"李教头",	"lv":1,	]),
([	"type":1,	"id":"chushi",	"name":"胖厨师",	"lv":1,	]),
([	"type":1,	"id":"shilong",	"name":"石龙",	"lv":5,	]),
([	"type":1,	"id":"bai suzhen",	"name":"白素贞",	"lv":5,	]),
([	"type":1,	"id":"jia bu",	"name":"贾布",	"lv":2		]),
([	"type":1,	"id":"shang sanniang","name":"桑三娘",	"lv":2,	]),
([	"type":1,	"id":"shangguan yun","name":"上官云",	"lv":3,	]),
([	"type":1,	"id":"snake",		"name":"黑冠巨蟒",	"lv":3,	]),
([	"type":1,	"id":"tongbai xiong","name":"童百熊",	"lv":3,	]),
([	"type":1,	"id":"wang cheng",	"name":"王诚",	"lv":2,	]),
([	"type":1,	"id":"yang lianting","name":"杨莲亭",	"lv":3,	]),
([	"type":1,	"id":"ao bai",	"name":"鳌拜",	"lv":4,	]),
([	"type":1,	"id":"kang qingwang","name":"康亲王",	"lv":2,	]),
([	"type":1,	"id":"zuo changsheng","name":"左常生",	"lv":1,	]),
([	"type":1,	"id":"xin huqiu",	"name":"辛虎丘",	"lv":1,	]),
([	"type":1,	"id":"lao denuo",	"name":"劳德诺",	"lv":2,	]),
([	"type":1,	"id":"lin pingzhi",	"name":"林平之",	"lv":1,	]),
([	"type":1,	"id":"duxing dao",	"name":"独行盗",	"lv":3,	]),
([	"type":1,	"id":"woman",		"name":"青衣妇人",	"lv":2,	]),
([	"type":1,	"id":"ren fanzi",	"name":"人贩子",	"lv":1,	]),
([	"type":1,	"id":"songque",	"name":"宋缺",	"lv":3,	]),
([	"type":1,	"id":"gao yanei",	"name":"高衙内",	"lv":4,	]),
([	"type":1,	"id":"ju jian",	"name":"菊剑",	"lv":1,	]),
([	"type":1,	"id":"lan jian",	"name":"兰剑",	"lv":2,	]),
([	"type":1,	"id":"mei jian",	"name":"梅剑",	"lv":2,	]),
([	"type":1,	"id":"zhu jian",	"name":"竹剑",	"lv":3,	]),
([	"type":1,	"id":"lu sao",	"name":"陆嫂",	"lv":4,	]),
([	"type":1,	"id":"qiu popo",	"name":"裘婆婆",	"lv":4,	]),
([	"type":1,	"id":"yu popo",	"name":"余婆婆",	"lv":4,	]),
([	"type":1,	"id":"cheng qingshuang","name":"程青霜","lv":4,	]),
([	"type":1,	"id":"zhou popo",	"name":"周婆婆",	"lv":4,	]),
([	"type":1,	"id":"feng popo",	"name":"冯婆婆",	"lv":3,	]),
([	"type":1,	"id":"fu mingyi",	"name":"符敏仪",	"lv":3,	]),
([	"type":1,	"id":"liu sao",	"name":"刘嫂",	"lv":3,	]),
([	"type":1,	"id":"shi sao",	"name":"石嫂",	"lv":3,	]),
([	"type":1,	"id":"dingjian",	"name":"丁坚",	"lv":2,	]),
([	"type":1,	"id":"shilingwei",	"name":"施令威",	"lv":1,	]),
([	"type":1,	"id":"zhuangding",	"name":"庄丁",	"lv":1,	]),
([	"type":1,	"id":"cha hetai",	"name":"察合台",	"lv":3,	]),
([	"type":1,	"id":"shu chi",	"name":"术赤",	"lv":4,	]),
([	"type":1,	"id":"zhao zhijing","name":"赵志敬",	"lv":2,	]),
([	"type":1,	"id":"eba",		"name":"恶霸",	"lv":2,	]),
([	"type":1,	"id":"sha shou",	"name":"杀手",	"lv":1,	]),
([	"type":1,	"id":"wang furen",	"name":"王夫人",	"lv":1,	]),
([	"type":1,	"id":"yao bodang",	"name":"姚伯当",	"lv":1,	]),
([	"type":1,	"id":"zhuang ding",	"name":"庄丁",	"lv":1,	]),
([	"type":1,	"id":"bo chen",	"name":"卜沉",	"lv":3,	]),
([	"type":1,	"id":"deng banian", "name":"邓八年",	"lv":2,	]),
([	"type":1,	"id":"di xiu",	"name":"狄修",	"lv":1,	]),
([	"type":1,	"id":"ding mian",	"name":"丁勉",	"lv":3,	]),
([	"type":1,	"id":"fei bing",	"name":"费彬",	"lv":3,	]),
([	"type":1,	"id":"gao kexin",	"name":"高克新",	"lv":2,	]),
([	"type":1,	"id":"lu bai",	"name":"陆柏",	"lv":4,	]),
([	"type":1,	"id":"sha tianjiang","name":"沙天江",	"lv":3,	]),
([	"type":1,	"id":"shi dengda",	"name":"史登达",	"lv":1,	]),
([	"type":1,	"id":"tang yinghu",	"name":"汤英鹄",	"lv":4,	]),
([	"type":1,	"id":"wan daping",	"name":"万大平",	"lv":1,	]),
([	"type":1,	"id":"yuji zi",	"name":"玉玑子",	"lv":4,	]),
([	"type":1,	"id":"zhang san",	"name":"张三",	"lv":1,	]),
([	"type":1,	"id":"caizhu",	"name":"张财主",	"lv":4,	]),
([	"type":1,	"id":"hufa",		"name":"护法",	"lv":1,	]),
([	"type":1,	"id":"leng chuanyun","name":"冷传云",	"lv":4,	]),
([	"type":1,	"id":"leng tanyue",	"name":"冷探月",	"lv":3,	]),
([	"type":1,	"id":"liang shiye",	"name":"梁师爷",	"lv":3,	]),
([	"type":1,	"id":"liusan",	"name":"刘三爷",	"lv":1,	]),
([	"type":1,	"id":"hou tonghai",	"name":"侯通海",	"lv":1,	]),
([	"type":1,	"id":"liang ziweng","name":"梁子翁",	"lv":1,	]),
([	"type":1,	"id":"lingzhi shangren","name":"灵智上人","lv":1,	]),
([	"type":1,	"id":"mei chaofeng","name":"梅超风",	"lv":2,	]),
([	"type":1,	"id":"sha tongtian","name":"沙通天",	"lv":1,	]),
([	"type":1,	"id":"wangye",	"name":"完颜洪烈",	"lv":1,	]),
([	"type":1,	"id":"wanyan kang",	"name":"完颜康",	"lv":2,	]),
([	"type":1,	"id":"da toumu",	"name":"野羊寨大头目","lv":2,	]),
([	"type":1,	"id":"yao boyi",	"name":"姚伯义",	"lv":3,	]),
([	"type":1,	"id":"jiasan",	"name":"贾三",	"lv":1,	]),
([	"type":1,	"id":"wu laoda",	"name":"乌老大",	"lv":4,	]),
([	"type":1,	"id":"hai dafu",	"name":"海大富",	"lv":3,	]),

(["type":1,	"id":"bei jinyi",		"name":"贝锦仪",	"lv":1,	]),
(["type":1,	"id":"jingdao shitai",	"name":"静道师太",	"lv":2,	]),
(["type":1,	"id":"fang bilin",		"name":"方碧琳",	"lv":1,	]),
(["type":1,	"id":"jingfeng shitai",	"name":"静风师太",	"lv":2,	]),
(["type":1,	"id":"jinghui shitai",	"name":"静慧师太",	"lv":2,	]),
(["type":1,	"id":"hui fan",		"name":"慧凡",	"lv":3,	]),
(["type":1,	"id":"jingjia shitai",	"name":"静迦师太",	"lv":2,	]),
(["type":1,	"id":"jingkong shitai",	"name":"静空师太",	"lv":2,	]),
(["type":1,	"id":"li mingxia",		"name":"李明霞",	"lv":1,	]),
(["type":1,	"id":"zhao lingzhu",	"name":"赵灵珠",	"lv":1,	]),
(["type":1,	"id":"ming jin",		"name":"明镜",	"lv":1,	]),
(["type":1,	"id":"su mengqing",		"name":"苏梦清",	"lv":1,	]),
(["type":1,	"id":"jingxian shitai",	"name":"静闲师太",	"lv":1,	]),
(["type":1,	"id":"jingxu shitai",	"name":"静虚师太",	"lv":2,	]),
(["type":1,	"id":"jingxuan shitai",	"name":"静玄师太",	"lv":2,	]),
(["type":1,	"id":"yong",			"name":"永庆和尚",	"lv":2,	]),
(["type":1,	"id":"wu jiang",		"name":"武将",	"lv":1,	]),
(["type":1,	"id":"da tusi",		"name":"大土司",	"lv":2,	]),
(["type":1,	"id":"huangmei dashi",	"name":"黄眉大师",	"lv":6,	]),
(["type":1,	"id":"huo xiansheng",	"name":"霍先生",	"lv":2,	]),
(["type":1,	"id":"mu wanqing",		"name":"木婉清",	"lv":2,	]),
(["type":1,	"id":"zu touren",		"name":"族头人",	"lv":2,	]),
(["type":1,	"id":"ba tianshi",		"name":"巴天石",	"lv":3,	]),
(["type":1,	"id":"dao baifeng",		"name":"刀白凤",	"lv":3,	]),
(["type":1,	"id":"fan ye",		"name":"范骅",	"lv":3,	]),
(["type":1,	"id":"fu sigui",		"name":"傅思归",	"lv":2,	]),
(["type":1,	"id":"gao shengtai",	"name":"高升泰",	"lv":5,	]),
(["type":1,	"id":"gu ducheng",		"name":"古笃诚",	"lv":2,	]),
(["type":1,	"id":"hua hegen",		"name":"华赫艮",	"lv":4,	]),
(["type":1,	"id":"zhu danchen",		"name":"朱丹臣",	"lv":2,	]),
(["type":1,	"id":"zhu wanli",		"name":"褚万里",	"lv":2,	]),
(["type":1,	"id":"fahai",			"name":"法海和尚",	"lv":5,	]),
(["type":1,	"id":"yi he",			"name":"仪和",	"lv":3,	]),
(["type":1,	"id":"yi lin",		"name":"仪琳",	"lv":2,	]),
(["type":1,	"id":"yi qing",		"name":"仪清",	"lv":3,	]),
(["type":1,	"id":"yi wen",		"name":"仪文",	"lv":2,	]),
(["type":1,	"id":"yi zhi",		"name":"仪质",	"lv":2,	]),
(["type":1,	"id":"aer tai",		"name":"阿尔泰",	"lv":2,	]),
(["type":1,	"id":"bai hanfeng",		"name":"白寒枫",	"lv":1,	]),
(["type":1,	"id":"chaer zhu",		"name":"察尔珠",	"lv":2,	]),
(["type":1,	"id":"duo long",		"name":"多隆",	"lv":4,	]),
(["type":1,	"id":"hai dafu",		"name":"海大富",	"lv":3,	]),
(["type":1,	"id":"shi wei",		"name":"皇宫侍卫",	"lv":2,	]),
(["type":1,	"id":"zhao qixian",		"name":"赵齐贤",	"lv":2,	]),
(["type":1,	"id":"shi wei",		"name":"御前侍卫",	"lv":2,	]),
(["type":1,	"id":"zhang kangnian",	"name":"张康年",	"lv":2,	]),
(["type":1,	"id":"rui dong",		"name":"瑞栋",	"lv":3,	]),
(["type":1,	"id":"ao bai",		"name":"鳌拜",	"lv":4,	]),
(["type":1,	"id":"xin huqiu",		"name":"辛虎丘",	"lv":1,	]),
(["type":1,	"id":"xiao xilou",		"name":"萧西楼",	"lv":1,	]),
(["type":1,	"id":"zhu xiawu",		"name":"朱侠武",	"lv":1,	]),
(["type":1,	"id":"yue lingshan",	"name":"岳灵珊",	"lv":1,	]),
(["type":1,	"id":"chen jialuo",		"name":"陈家洛",	"lv":4,	]),
(["type":1,	"id":"huo ayi",		"name":"霍阿伊",	"lv":2,	]),
(["type":1,	"id":"huo qingtong",	"name":"霍青桐",	"lv":2,	]),
(["type":1,	"id":"oldman",		"name":"说书老人",	"lv":2,	]),
(["type":1,	"id":"gao jinchang",	"name":"高进昌",	"lv":3,	]),
(["type":1,	"id":"gong zi",		"name":"富家公子",	"lv":1,	]),
(["type":1,	"id":"lu yuhou",		"name":"陆虞候",	"lv":1,	]),
(["type":1,	"id":"qing yi",		"name":"青衣",	"lv":2,	]),
(["type":1,	"id":"zhifa zhanglao",	"name":"智法长老",	"lv":4,	]),
(["type":1,	"id":"xiao sheng",		"name":"小生",	"lv":3,	]),
(["type":1,	"id":"wang chao",		"name":"王朝",	"lv":4,	]),
(["type":1,	"id":"ma han",		"name":"马汉",	"lv":4,	]),
(["type":1,	"id":"jian zhanglao",	"name":"简长老",	"lv":3,	]),
(["type":1,	"id":"liang zhanglao",	"name":"梁长老",	"lv":3,	]),
(["type":1,	"id":"peng zhanglao",	"name":"彭长老",	"lv":4,	]),
(["type":1,	"id":"lu youjiao",		"name":"鲁有脚",	"lv":2,	]),
(["type":1,	"id":"danqing sheng",	"name":"丹青生",	"lv":2,	]),
(["type":1,	"id":"heibai zi",		"name":"黑白子",	"lv":4,	]),
(["type":1,	"id":"huangzhong gong",	"name":"黄钟公",	"lv":5,	]),
(["type":1,	"id":"tubi weng",		"name":"秃笔翁",	"lv":3,	]),
(["type":1,	"id":"xiaoshidi",		"name":"小师弟",	"lv":1,	]),
(["type":1,	"id":"guo jing",		"name":"郭靖",	"lv":5,	]),
(["type":1,	"id":"boer shu",		"name":"博尔术",	"lv":5,	]),
(["type":1,	"id":"hua zheng",		"name":"华筝公主",	"lv":3,	]),
(["type":1,	"id":"qin bing",		"name":"巡逻亲兵",	"lv":4,	]),
(["type":1,	"id":"jinwei bing",		"name":"近卫兵",	"lv":4,	]),
(["type":1,	"id":"hao datong",		"name":"郝大通",	"lv":3,	]),
(["type":1,	"id":"li zhichang",		"name":"李志常",	"lv":2,	]),
(["type":1,	"id":"liu chuxuan",		"name":"刘处玄",	"lv":3,	]),
(["type":1,	"id":"ma yu",			"name":"马钰",	"lv":3,	]),
(["type":1,	"id":"qi zhicheng",		"name":"祁志诚",	"lv":2,	]),
(["type":1,	"id":"qiu chuji",		"name":"丘处机",	"lv":3,	]),
(["type":1,	"id":"sun buer",		"name":"孙不二",	"lv":3,	]),
(["type":1,	"id":"tan chuduan",		"name":"谭处端",	"lv":3,	]),
(["type":1,	"id":"wang chuyi",		"name":"王处一",	"lv":3,	]),
(["type":1,	"id":"yin zhiping",		"name":"尹志平",	"lv":2,	]),
(["type":1,	"id":"zhangyuan",		"name":"掌园道长",	"lv":2,	]),
(["type":1,	"id":"bao butong",		"name":"包不同",	"lv":3,	]),
(["type":1,	"id":"lao fangzhang",	"name":"老方丈",	"lv":1,	]),
(["type":1,	"id":"makepilo",		"name":"马可皮罗",	"lv":1,	]),
(["type":1,	"id":"deng baichuan",	"name":"邓百川",	"lv":4,	]),
(["type":1,	"id":"feng boe",		"name":"风波恶",	"lv":2,	]),
(["type":1,	"id":"gongye qian",		"name":"公冶乾",	"lv":3,	]),
(["type":1,	"id":"yao hou",		"name":"乐厚",	"lv":2,	]),
(["type":1,	"id":"jianchu daoren",	"name":"建除道人",	"lv":1,	]),
(["type":1,	"id":"tianbai daoren",	"name":"天柏道人",	"lv":2,	]),
(["type":1,	"id":"tiansong daoren",	"name":"天松道人",	"lv":3,	]),
(["type":1,	"id":"tianyi daoren",	"name":"天乙道人",	"lv":3,	]),
(["type":1,	"id":"xuncha shi",		"name":"泰山寻察使","lv":3,	]),
(["type":1,	"id":"mo shenggu",		"name":"莫声谷",	"lv":2,	]),
(["type":1,	"id":"song yuanqiao",	"name":"宋远桥",	"lv":3,	]),
(["type":1,	"id":"zhang songxi",	"name":"张松溪",	"lv":2,	]),
(["type":1,	"id":"yu daiyan",		"name":"俞岱岩",	"lv":2,	]),
(["type":1,	"id":"yu lianzhou",		"name":"俞莲舟",	"lv":4,	]),
(["type":1,	"id":"yin litin",		"name":"殷梨亭",	"lv":2,	]),
(["type":1,	"id":"liusan",		"name":"刘三爷",	"lv":2,	]),
(["type":1,	"id":"baiyi ren",		"name":"白衣人",	"lv":1,	]),
(["type":1,	"id":"mingxin",		"name":"明性",	"lv":2,	]),
(["type":1,	"id":"bilian",		"name":"碧涟",	"lv":1,	]),
(["type":1,	"id":"shangren",		"name":"雪山上人",	"lv":4,	]),
(["type":1,	"id":"zhanglao",		"name":"猿长老",	"lv":2,	]),
(["type":1,	"id":"zhengbanqiao",	"name":"郑板桥",	"lv":4,	]),
(["type":1,	"id":"mu nianci",		"name":"穆念慈",	"lv":2,	]),
([	"type":1,	"id":"li tianyuan",	"name":"李天垣",	"lv":1,	]),
([	"type":1,	"id":"peng yingyu",	"name":"彭莹玉",	"lv":1,	]),
([	"type":1,	"id":"shuo bude",	"name":"说不得",["type":1,	"id":"mo shenggu",		"name":"莫声谷",	"lv":2,	]),
(["type":1,	"id":"song yuanqiao",	"name":"宋远桥",	"lv":3,	]),
(["type":1,	"id":"zhang songxi",	"name":"张松溪",	"lv":2,	]),
(["type":1,	"id":"yu daiyan",		"name":"俞岱岩",	"lv":2,	]),
(["type":1,	"id":"yu lianzhou",		"name":"俞莲舟",	"lv":4,	]),
(["type":1,	"id":"yin litin",		"name":"殷梨亭",	"lv":2,	]),
(["type":1,	"id":"liusan",		"name":"刘三爷",	"lv":2,	]),
(["type":1,	"id":"baiyi ren",		"name":"白衣人",	"lv":1,	]),
(["type":1,	"id":"mingxin",		"name":"明性",	"lv":2,	]),
(["type":1,	"id":"bilian",		"name":"碧涟",	"lv":1,	]),
(["type":1,	"id":"shangren",		"name":"雪山上人",	"lv":4,	]),
(["type":1,	"id":"zhanglao",		"name":"猿长老",	"lv":2,	]),
(["type":1,	"id":"zhengbanqiao",	"name":"郑板桥",	"lv":4,	]),
(["type":1,	"id":"mu nianci",		"name":"穆念慈",	"lv":2,	]),
([	"type":1,	"id":"li tianyuan",	"name":"李天垣",	"lv":1,	]),
([	"type":1,	"id":"peng yingyu",	"name":"彭莹玉",	"lv":1,	]),
([	"type":1,	"id":"shuo bude",	"name":"说不得",	"lv":1,	]),
([	"type":1,	"id":"tang yang",	"name":"唐洋",	"lv":1,	]),
([	"type":1,	"id":"wen song",	"name":"闻松",	"lv":1,	]),
([	"type":1,	"id":"xin ran",	"name":"辛然",	"lv":1,	]),
([	"type":1,	"id":"zhou dian",	"name":"周颠",	"lv":1,	]),
([	"type":1,	"id":"zhang zhong",	"name":"张中",	"lv":1,	]),
([	"type":1,	"id":"yin wushou",	"name":"殷无寿",	"lv":1,	]),
([	"type":1,	"id":"yin wulu",	"name":"殷无禄",	"lv":1,	]),
([	"type":1,	"id":"yin wufu",	"name":"殷无福",	"lv":1,	]),
([	"type":1,	"id":"dai qisi",	"name":"黛绮丝",	"lv":3,	]),
([	"type":1,	"id":"fan yao",	"name":"范遥",	"lv":4,	]),
([	"type":1,	"id":"wei yixiao",	"name":"韦一笑",	"lv":3,	]),
([	"type":1,	"id":"xie xun",	"name":"谢逊",	"lv":3,	]),
([	"type":1,	"id":"yang xiao",	"name":"杨逍",	"lv":5,	]),
([	"type":1,	"id":"yin tianzheng","name":"殷天正",	"lv":3,	]),
([	"type":1,	"id":"yin yewang",	"name":"殷野王",	"lv":2,	]),
([	"type":1,	"id":"wu liuqi",	"name":"吴六奇",	"lv":4,	]),
([	"type":1,	"id":"xu tianchuan","name":"徐天川",	"lv":5,	]),
([	"type":1,	"id":"qian laoben",	"name":"钱老本",	"lv":1,	]),


([	"type":2,	"id":"golden ring",		"name":"金戒指",		"lv":2,]),
([	"type":2,	"id":"fuchen",		"name":"拂尘",		"lv":1,]),
([	"type":2,	"id":"jia sha",		"name":"金边黑布袈裟",	"lv":2,]),
([	"type":2,	"id":"pao",			"name":"青色道袍",		"lv":1,]),
([	"type":2,	"id":"jia sha",		"name":"灰布镶边袈裟",	"lv":2,]),
([	"type":2,	"id":"yao qin",		"name":"瑶琴",		"lv":2,]),
([	"type":2,	"id":"cloth",			"name":"迦裟",		"lv":1,]),
([      "type":2,       "id":"card1",                   "name":"风雷堂令牌",   "lv":3, ]),
([	"type":1,	"id":"fan yao",	"name":"范遥",	"lv":4,	]),
([	"type":1,	"id":"wei yixiao",	"name":"韦一笑",	"lv":3,	]),
([	"type":1,	"id":"xie xun",	"name":"谢逊",	"lv":3,	]),
([	"type":1,	"id":"yang xiao",	"name":"杨逍",	"lv":5,	]),
([	"type":1,	"id":"yin tianzheng","name":"殷天正",	"lv":3,	]),
([	"type":1,	"id":"yin yewang",	"),


([      "type":2,       "id":"golden ring",             "name":"金戒指",                "lv":2,]),
([      "type":2,       "id":"fuchen",          "name":"拂尘",          "lv":1,]),
([	"type":2,	"id":"jia sha",		"name":"金边黑布袈裟",	"lv":2,]),
([	"type":2,	"id":"pao",			"name":"青色道袍",		"lv":1,]),
([	"type":2,	"id":"jia sha",		"name":"灰布镶边袈裟",	"lv":2,]),
([	"type":2,	"id":"yao qin",		"name":"瑶琴",		"lv":2,]),
([	"type":2,	"id":"cloth",			"name":"迦裟",		"lv":1,]),
([      "type":2,       "id":"card1",                   "name":"风雷堂令牌",   "lv":3, ]),
([	"type":1,	"id":"fan yao",	"name":"范遥",	"lv":4,	]),
([	"type":1,	"id":"wei yixiao",	"name":"韦一笑",	"lv":3,	]),
([	"type":1,	"id":"xie xun",	"name":"谢逊",	"lv":3,	]),
([	"type":1,	"id":"yang xiao",	"name":"杨逍",	"lv":5,	]),
([	"type":1,	"id":"yin tianzheng","name":"殷天正",	"lv":3,	]),
([	"type":1,	"id":"yin yewang",	"name":"殷野王",	"lv":2,	]),
([	"type":1,	"id":"wu liuqi",	"name":"吴六奇",	"lv":4,	]),
([	"type":1,	"id":"xu tianchuan","name":"徐天川",	"lv":5,	]),
([	"type":1,	"id":"qian laoben",	"name":"钱老本",	"lv":1,	]),


([	"type":2,	"id":"golden ring",		"name":"金戒指",		"lv":2,]),
([	"type":2,	"id":"fuchen",		"name":"拂尘",		"lv":1,]),
([	"type":2,	"id":"jia sha",		"name":"金边黑布袈裟",	"lv":2,]),
([	"type":2,	"id":"pao",			"name":"青色道袍",		"lv":1,]),
([	"type":2,	"id":"jia sha",		"name":"灰布镶边袈裟",	"lv":2,]),
([	"type":2,	"id":"yao qin",		"name":"瑶琴",		"lv":2,]),
([	"type":2,	"id":"cloth",			"name":"迦裟",		"lv":1,]),
([	"type":2,	"id":"card1",			"name":"风雷堂令牌",	"lv":3,]),
([	"type":2,	"id":"card2",			"name":"白虎堂令牌",	"lv":3,]),
([	"type":2,	"id":"card3",			"name":"青龙堂令牌",	"lv":3,]),
([	"type":2,	"id":"card4",			"name":"天香堂令牌",	"lv":3,]),
([	"type":2,	"id":"zhenzhu",		"name":"大珍珠",		"lv":3,]),
([	"type":2,	"id":"book",			"name":"《四十二章经》",	"lv":2,]),
([	"type":2,	"id":"daode jing",		"name":"《道德经》",	"lv":1,]),
([	"type":2,	"id":"gaoyao",		"name":RED"膏"BLK"药"NOR,	"lv":1,]),
([	"type":2,	"id":"key",			"name":CYN"青铜钥匙"NOR,	"lv":3,]),
([	"type":2,	"id":"yu pei",		"name":HIC"玉佩"NOR,	"lv":1,]),
([	"type":2,	"id":"sword",			"name":"白练分水剑",	"lv":3,]),
([	"type":2,	"id":"sword",			"name":"扁诸神剑",		"lv":3,]),
([	"type":2,	"id":"duan di",		"name":HIG "短笛" NOR,	"lv":1,]),
([	"type":2,	"id":"er hu",			"name":HIY"二胡"NOR,	"lv":1,]),
([	"type":2,	"id":"sword",			"name":"古松残阙",		"lv":3,]),
([	"type":2,	"id":"ping",		"name":HIC"雨后天青双耳瓶"NOR,	"lv":1,]),
([	"type":2,	"id":"shenxiang",	"name":HIW"白衣送子观音像"NOR,	"lv":1,]),
([	"type":2,	"id":"haier zheng",	"name":HIC"水蓝陶瓷孩儿枕"NOR,	"lv":1,]),
([	"type":2,	"id":"qiankun hu",	"name":HIR"玫瑰红乾坤壶"NOR,	"lv":1,]),
([	"type":2,	"id":"jinpin",	"name":HIW"乳白水净瓶"NOR,		"lv":1,]),
([	"type":2,	"id":"cloth",			"name":"五福朝寿衣",	"lv":2,]),
([	"type":2,	"id":"guai zhang",		"name":"龙头拐杖",		"lv":2,]),
([	"type":2,	"id":"guijia",		"name":"黑色龟甲",		"lv":1,]),
([	"type":2,	"id":"jing",		"name":"《金刚般若波罗蜜经》",	"lv":1,]),
([	"type":2,	"id":"jing",		"name":"《妙法莲花经》",		"lv":1,]),
([	"type":2,	"id":"jing",		"name":"《维摩诘所说经》",		"lv":1,]),
([	"type":2,	"id":"jing",		"name":"《萨昙分陀利经》",		"lv":1,]),
([	"type":2,	"id":"jian pu",		"name":"天羽奇剑剑谱",	"lv":2,]),
([	"type":2,	"id":"baiyun wan",		"name":"白云熊胆丸",	"lv":2,]),
([	"type":2,	"id":"pao",			"name":WHT"灰色道袍"NOR,	"lv":1,]),
([	"type":2,	"id":"pao",			"name":HIG"青色道袍"NOR,	"lv":1,]),
([	"type":2,	"id":"shouwu",		"name":WHT"何首乌"NOR,	"lv":2,]),
([	"type":2,	"id":"fuchen",		"name":"乌柄拂尘",		"lv":1,]),
([	"type":2,	"id":"guan fu",		"name":"五品官服",		"lv":2,]),
([	"type":2,	"id":"chang pao",		"name":"阿拉伯长袍",	"lv":1,]),
([	"type":2,	"id":"daopao",		"name":"破道袍",		"lv":1,]),
([	"type":2,	"id":"cloth",			"name":"太极道袍",		"lv":3,]),
([	"type":2,	"id":"wan dao",		"name":"阿拉伯弯刀",	"lv":1,]),
([	"type":2,	"id":"yayi cloth",		"name":"衙役服",		"lv":1,]),
([	"type":2,	"id":"roujing sword",	"name":"柔金锋",		"lv":4,]),
([	"type":2,	"id":"zijin chui",		"name":"紫金锤",		"lv":3,]),
([	"type":2,	"id":"tie suanpan",		"name":"铁算盘",		"lv":2,]),
([	"type":2,	"id":"yinyang-sword",	"name":"阴阳剑",		"lv":3,]),
([	"type":2,	"id":"yin zhen",		"name":"银针",		"lv":1,]),
([	"type":2,	"id":"canhezhi",		"name":"参合指要诀",	"lv":2,]),
([	"type":2,	"id":"tanyunshou",		"name":"探云手要诀",	"lv":1,]),
([	"type":2,	"id":"tuling fu",		"name":"土灵符",		"lv":1,]),
([	"type":2,	"id":"shan",			"name":"鹅黄绸衫",		"lv":2,]),
([	"type":2,	"id":"shan",			"name":"藕色纱衫",		"lv":2,]),
([	"type":2,	"id":"shu",			"name":"太极十三势",	"lv":2,]),
([	"type":2,	"id":"nuer xiang",		"name":"女儿香",		"lv":1,]),
([	"type":2,	"id":"duanyan",		"name":"端砚",		"lv":1,]),
([	"type":2,	"id":"hu pi",			"name":HIY"虎皮"NOR,	"lv":3,]),
([	"type":2,	"id":"baiyu xiao",		"name":"白玉箫",		"lv":2,]),
([	"type":2,	"id":"iron spear",		"name":"半截铁枪",		"lv":1,]),
([	"type":2,	"id":"junfu",			"name":"军服",		"lv":2,]),
([	"type":2,	"id":"ziyi",			"name":"灰色淄衣",		"lv":2,]),
([	"type":2,	"id":"hanyangan",		"name":"旱烟杆",		"lv":1,]),
([	"type":2,	"id":"hammer",		"name":"金刚杵",		"lv":3,]),
([	"type":2,	"id":"niu jiao",		"name":"金牛角",		"lv":3,]),
([	"type":2,	"id":"xifu",			"name":"西服",		"lv":1,]),
([	"type":2,	"id":"yan",			"name":"香烟",		"lv":1,]),
([	"type":2,	"id":"yuzuizi",		"name":"玉坠子",		"lv":1,]),
([	"type":2,	"id":"yuzhuo",		"name":"玉镯",		"lv":1,]),
([	"type":2,	"id":"zi_zhuzhang",		"name":"紫竹杖",		"lv":1,]),
([	"type":2,	"id":"zuanshijiezhi",	"name":"钻石戒指",		"lv":2,]),
([	"type":2,	"id":"iron spear",		"name":"铁枪",		"lv":1,]),
([	"type":2,	"id":"xiao huolu",		"name":"红泥小火炉",	"lv":1,]),
([	"type":2,	"id":"xiong dan",		"name":"熊胆",		"lv":1,]),
([	"type":2,	"id":"tie li",		"name":"残破铁犁",		"lv":1,]),
([	"type":2,	"id":"yao chu",		"name":"药锄",		"lv":1,]),
([	"type":2,	"id":"jiaohuaji",		"name":"叫化鸡",		"lv":1,]),
([	"type":2,	"id":"meigui",		"name":HIR"红玫瑰"NOR,	"lv":1,]),
([	"type":2,	"id":"cui yuzhuo",		"name":HIC"翠玉镯"NOR,	"lv":1,]),
([	"type":2,	"id":"skirt",			"name":"粗布裙",		"lv":1,]),
([	"type":2,	"id":"cloth",			"name":"蓝色短褂",		"lv":1,]),
([	"type":2,	"id":"feicui qun",		"name":"翡翠长裙",		"lv":1,]),
([	"type":2,	"id":"cloth",			"name":"淡黄衫",		"lv":1,]),
([	"type":2,	"id":"hubi",			"name":"湖笔",		"lv":1,]),
([	"type":2,	"id":"deadleaf",		"name":"枯黄的叶",		"lv":2,]),
([	"type":2,	"id":"qian",			"name":"灵签",		"lv":2,]),
([	"type":2,	"id":"dou peng",		"name":"斗篷",		"lv":1,]),
([	"type":2,	"id":"junfu",			"name":"锦衣军服",		"lv":1,]),
([	"type":2,	"id":"junfu",			"name":"黄衣军服",		"lv":1,]),
([	"type":2,	"id":"fangsha ji",		"name":"纺纱机",		"lv":1,]),
([	"type":2,	"id":"jin duan",		"name":"锦缎",		"lv":1,]),
([	"type":2,	"id":"laoshan shen",	"name":"老山参",		"lv":2,]),
([	"type":2,	"id":"mudi",			"name":"牧笛",		"lv":1,]),
([	"type":2,	"id":"muyu",			"name":"木鱼",		"lv":1,]),
([	"type":2,	"id":"ruanjian",		"name":"软剑",		"lv":2,]),
([	"type":2,	"id":"hua ban",		"name":"花瓣",		"lv":1,]),
([	"type":2,	"id":"qingyi",		"name":"青衣",		"lv":1,]),
([	"type":2,	"id":"zhuzhang",		"name":"青竹杖",		"lv":1,]),
([	"type":2,	"id":"qingshu",		"name":"情书",		"lv":3,]),
([	"type":2,	"id":"shoupa",		"name":"手帕",		"lv":2,]),
([	"type":2,	"id":"gao",			"name":"冰雪翡翠糕",	"lv":1,]),
([	"type":2,	"id":"gujian",		"name":"古剑",		"lv":2,]),
([	"type":2,	"id":"leigong hong",	"name":"雷公轰",		"lv":1,]),
([	"type":2,	"id":"hat",			"name":"银色皮帽",		"lv":1,]),
([	"type":2,	"id":"jin duan",		"name":"锦缎",		"lv":1,]),
([	"type":2,	"id":"wuliangye",		"name":"五粮液",		"lv":2,]),
([	"type":2,	"id":"beike",			"name":"贝壳",		"lv":1,]),
([	"type":2,	"id":"wucai beike",		"name":"五彩贝壳",		"lv":2,]),
([	"type":2,	"id":"yu",			"name":HIC"青龙碧血玉"NOR,	"lv":3,]),
([	"type":2,	"id":"jiangjunzhang",	"name":"将军杖",		"lv":3,]),
([	"type":2,	"id":"pomodao",		"name":"泼墨刀",		"lv":3,]),
([	"type":2,	"id":"qixianjian",		"name":"七弦剑",		"lv":3,]),
([	"type":2,	"id":"weiqizi",		"name":"围棋子",		"lv":3,]),

(["type":3,	"id":"/d/baituo/zhulin",		"name":"白驼山竹林",	"lv":1,]),
(["type":3,	"id":"/d/baituo/cave1",		"name":"白驼山岩洞内",	"lv":1,]),
(["type":3,	"id":"/d/baituo/cedong",		"name":"侧洞",		"lv":1,]),
(["type":3,	"id":"/d/chengdu/wenzai/dating",	"name":"温家大厅",		"lv":2,]),
(["type":3,	"id":"/d/chengdu/shandao3",	"name":"山洞口",		"lv":3,]),
(["type":3,	"id":"/d/dali/heisenlin",		"name":"黑森林",		"lv":1,]),
(["type":3,	"id":"/d/dali/yangzong",		"name":"阳宗镇",		"lv":2,]),
(["type":3,	"id":"/d/dali/buxiongbu",		"name":"步雄部",		"lv":1,]),
(["type":3,	"id":"/d/dali/yuxiashan",		"name":"玉霞山",		"lv":2,]),
(["type":3,	"id":"/d/dali/xizhou",		"name":"喜州城",		"lv":1,]),
(["type":3,	"id":"/d/dali/wuding",		"name":"武定镇",		"lv":2,]),
(["type":3,	"id":"/d/dali/luwang",		"name":"鲁望镇",		"lv":1,]),
(["type":3,	"id":"/d/dali/hexi",		"name":"河西镇",		"lv":2,]),
(["type":3,	"id":"/d/dali/longkou",		"name":"龙口城",		"lv":1,]),
(["type":3,	"id":"/d/tianlongsi/tading",	"name":"舍利塔塔顶",	"lv":2,]),
(["type":3,	"id":"/d/emei/gate",		"name":"凤凰坪",		"lv":2,]),
(["type":3,	"id":"/d/emei/ningcui",		"name":"凝翠楼",		"lv":2,]),
(["type":3,	"id":"/d/emei/qixiang",		"name":"七香轩",		"lv":2,]),
(["type":3,	"id":"/d/emei/huaying",		"name":"花影亭",		"lv":2,]),
(["type":3,	"id":"/d/emei/ligouyuan",		"name":"离垢园",		"lv":2,]),
(["type":3,	"id":"/d/emei/huayantin",		"name":"华严宝塔亭",	"lv":2,]),
(["type":3,	"id":"/d/emei/hongchun",		"name":"洪椿坪",		"lv":2,]),
(["type":3,	"id":"/d/emei/dongzhong",		"name":"九老仙府",		"lv":3,]),
(["type":3,	"id":"/d/emei/tianju",		"name":"天心居",		"lv":3,]),
(["type":3,	"id":"/d/hainan/xuanya",		"name":"悬崖秘洞",		"lv":3,]),
(["type":3,	"id":"/d/hainan/cave3",		"name":"落笔洞",		"lv":3,]),
(["type":3,	"id":"/d/hainan/underhill",	"name":"琼崖下",		"lv":2,]),
(["type":3,	"id":"/d/hainan/baiyunan",		"name":"白云庵",		"lv":3,]),
(["type":3,	"id":"/d/hengshan/xuankong1",	"name":"悬空寺北楼",	"lv":2,]),
(["type":3,	"id":"/d/hengshan/cuipinggu2",	"name":"翠屏谷",		"lv":2,]),
(["type":3,	"id":"/d/hengshan/sanjiaodian",	"name":"三教殿",		"lv":2,]),
(["type":3,	"id":"/d/hengshan/yunge",		"name":"云阁虹桥",		"lv":2,]),
(["type":3,	"id":"/d/hengshan/xuangengsong",	"name":"悬根松",		"lv":2,]),
(["type":3,	"id":"/d/hengshan/tongyuangu",	"name":"通元谷",		"lv":2,]),
(["type":3,	"id":"/d/hengshan/jijiaoshi",	"name":"鸡叫石",		"lv":2,]),
(["type":3,	"id":"/d/hengshan/kutianjing",	"name":"苦甜井",		"lv":2,]),
(["type":3,	"id":"/d/hengshan/huixiantai",	"name":"会仙台",		"lv":2,]),
(["type":3,	"id":"/d/huanggon/dawu",		"name":"海大富居处",	"lv":1,]),
(["type":3,	"id":"/d/huanggon/junjichu",	"name":"军机处",		"lv":1,]),
(["type":3,	"id":"/d/huanggon/wumen",		"name":"午门",		"lv":1,]),
(["type":3,	"id":"/d/huanggon/ciqinggon",	"name":"太后寝宫",		"lv":1,]),
(["type":3,	"id":"/d/huanhua/hriver_room",	"name":"观鱼阁",		"lv":1,]),
(["type":3,	"id":"/d/huanhua/jhongqiao",	"name":"霁虹桥",		"lv":2,]),
(["type":3,	"id":"/d/huanhua/yxiangge",	"name":"聆香阁",		"lv":1,]),
(["type":3,	"id":"/d/huanhua/hhxi",		"name":"浣花溪",		"lv":2,]),
(["type":3,	"id":"/d/huanhua/jt_cave1",	"name":"见天洞内",		"lv":1,]),
(["type":3,	"id":"/d/huashan/lianhua",		"name":"莲花峰",		"lv":2,]),
(["type":3,	"id":"/d/huashan/chengxiang",	"name":"沉香劈山处",	"lv":1,]),
(["type":3,	"id":"/d/huashan/yunu",		"name":"玉女峰",		"lv":2,]),
(["type":3,	"id":"/d/huashan/xiuxishi",	"name":"华山小筑",		"lv":1,]),
(["type":3,	"id":"/d/huashan/luoyan",		"name":"落雁峰",		"lv":3,]),
(["type":3,	"id":"/d/japan/liushengfu",	"name":"柳生府",		"lv":3,]),
(["type":3,	"id":"/d/japan/xiangpu",		"name":"土肥原相扑屋",	"lv":2,]),
(["type":3,	"id":"/d/japan/shuwu",		"name":"朝野书屋",		"lv":3,]),
(["type":3,	"id":"/d/japan/haixian",		"name":"海鲜馆",		"lv":2,]),
(["type":3,	"id":"/d/japan/yijiguan",		"name":"艺妓馆",		"lv":3,]),
(["type":3,	"id":"/d/japan/nanmen",		     "name":    "神户南门",	"lv":2,]),
(["type":3,     "id":"/d/japan/dongmen",                "name":"神户东门",              "lv":3,]),
(["type":3,	"id":"/d/lingjiu/xianchou",	"name":"仙愁门",		"lv":2,]),
(["type":3,	"id":"/d/lingjiu/dating",		"name":"独尊厅",		"lv":2,]),
(["type":3,	"id":"/d/lingjiu/biguan",		"name":"闭关室",		"lv":3,]),
(["type":3,	"id":"/d/lingjiu/mishi",		"name":"独尊密室",		"lv":3,]),
(["type":3,	"id":"/d/lingjiu/wuqiku",		"name":"蓼风轩",		"lv":2,]),
(["type":3,	"id":"/d/lingjiu/liangong",	"name":"戏凤阁",		"lv":3,]),
(["type":3,	"id":"/d/lingjiu/chufang",		"name":"藕香榭",		"lv":3,]),
(["type":3,	"id":"/d/lingjiu/qiushi",		"name":"囚室",		"lv":2,]),
(["type":3,	"id":"/d/lingjiu/xuanbing",	"name":"玄冰室",		"lv":2,]),
(["type":3,	"id":"/d/lingjiu/caifeng",		"name":"潇湘馆",		"lv":2,]),
(["type":3,	"id":"/d/quanzhen/xiaohuayuan1",	"name":"重阳园",		"lv":3,]),
(["type":3,	"id":"/d/quanzhen/shandong",	"name":"后山山洞",		"lv":3,]),
(["type":3,	"id":"/d/quanzhen/mishi",		"name":"全真密室",		"lv":3,]),
(["type":3,	"id":"/d/suzhou/gongdetading",	"name":"功德塔顶",		"lv":2,]),
(["type":3,	"id":"/d/suzhou/shelitading",	"name":"舍利塔顶",		"lv":2,]),
(["type":3,	"id":"/d/suzhou/canhe/huanshi",	"name":"还施水阁",		"lv":2,]),
(["type":3,	"id":"/d/suzhou/canhe/canhe",	"name":"参合山庄",		"lv":2,]),
(["type":3,	"id":"/d/suzhou/qinyun/tingyu",	"name":"听雨居",		"lv":2,]),
(["type":3,	"id":"/d/suzhou/qinyun/qinyun",	"name":"琴韵小筑",		"lv":2,]),
(["type":3,	"id":"/d/suzhou/tingxiang/txmen",	"name":"听香水榭",		"lv":2,]),
(["type":3,	"id":"/d/suzhou/tingxiang/wuxue",	"name":"无雪堂",		"lv":2,]),
(["type":3,	"id":"/d/suzhou/tuoman/tuoman",	"name":"曼陀山庄",		"lv":2,]),
(["type":3,	"id":"/d/suzhou/tuoman/hongxia",	"name":"红霞楼",		"lv":2,]),
(["type":3,	"id":"/d/suzhou/tuoman/loushang",	"name":"云锦楼上",		"lv":2,]),
(["type":3,	"id":"/d/taishan/yitian",		"name":"一天门",		"lv":1,]),
(["type":3,	"id":"/d/taishan/shengxian",	"name":"升仙坊",		"lv":2,]),
(["type":3,	"id":"/d/taishan/shixin",		"name":"试心石",		"lv":1,]),
(["type":3,	"id":"/d/taishan/yuhuang",		"name":"玉皇顶",		"lv":2,]),
(["type":3,	"id":"/d/taishan/beitian",		"name":"北天门",		"lv":1,]),
(["type":3,	"id":"/d/wudang/shesheng",		"name":"舍身崖",		"lv":3,]),
(["type":3,	"id":"/d/wudang/langmei",		"name":"榔梅园",		"lv":2,]),
(["type":3,	"id":"/d/wudang/wuyalin",		"name":"乌鸦岭",		"lv":3,]),
(["type":3,	"id":"/d/wudang/hutou",		"name":"虎头岩",		"lv":2,]),
(["type":3,	"id":"/d/wudang/santian",		"name":"三天门",		"lv":3,]),
(["type":3,	"id":"/d/wudang/xiaoyuan",		"name":"金殿",		"lv":2,]),
(["type":3,	"id":"/d/yandang/xiaolongq",	"name":"小龙湫",		"lv":1,]),
(["type":3,	"id":"/d/yandang/luoyan27",	"name":"天一阁",		"lv":1,]),
(["type":3,	"id":"/d/yandang/luoyan33",	"name":"中折瀑",		"lv":1,]),
(["type":3,	"id":"/d/yandang/luoyan38",	"name":"喷泉",		"lv":1,]),
(["type":3,	"id":"/d/yandang/luoyan37",	"name":"西花厅",		"lv":1,]),
(["type":3,	"id":"/d/yandang/luoyan25",	"name":"冷雁池塘",		"lv":1,]),
(["type":3,	"id":"/d/yandang/shandong6",	"name":"玲珑洞",		"lv":1,]),
(["type":3,	"id":"/d/yandang/shandong4",	"name":"隐虎洞",		"lv":1,]),
(["type":3,	"id":"/d/yandang/guanyin",		"name":"观音洞",		"lv":1,]),
(["type":3,	"id":"/d/yandang/xiyaotai",	"name":"西瑶台",		"lv":1,]),
(["type":3,	"id":"/d/yanjing/zhongyuan",	"name":"王府中院",		"lv":1,]),
(["type":3,	"id":"/d/yanjing/xiangxue",	"name":"香雪厅",		"lv":1,]),
(["type":3,	"id":"/d/yanjing/cave1",		"name":"王府土室",		"lv":1,]),
(["type":3,	"id":"/d/yanjing/intielao",	"name":"铁牢内",		"lv":2,]),
(["type":3,	"id":"/d/yanjing/liangziweng",	"name":"梁子翁居处",	"lv":2,]),
(["type":3,	"id":"/d/taiwan/house",		"name":"渔夫的家",		"lv":3,]),
(["type":3,	"id":"/d/taiwan/tree4",		"name":"风波林",		"lv":3,]),
(["type":3,	"id":"/d/taiwan/zhuanyuan",	"name":"庄家老屋",		"lv":3,]),
(["type":3,	"id":"/d/taiwan/xiaolou",		"name":"依红楼",		"lv":3,]),
(["type":3,	"id":"/d/taiwan/boss",		"name":"巨大山洞",		"lv":3,]),
(["type":3,	"id":"/d/dali/wfdating",		"name":"镇南王府大厅",	"lv":2,]),
(["type":3,	"id":"/d/dali/chahua1",		"name":"茶花园门",		"lv":2,]),
(["type":3,	"id":"/d/zhongzhou/fuwu",		"name":"休闲中心大堂yandang/guanyin",		"name":"观音洞",		"lv":1,]),
(["type":3,	"id":"/d/yandang/xiyaotai",	"name":"西瑶台",		"lv":1,]),
(["type":3,	"id":"/d/yanjing/zhongyuan",	"name":"王府中院",		"lv":1,]),
(["type":3,	"id":"/d/yanjing/xiangxue",	"name":"香雪厅",		"lv":1,]),
(["type":3,	"id":"/d/yanjing/cave1",		"name":"王府土室",		"lv":1,]),
(["type":3,	"id":"/d/yanjing/intielao",	"name":"铁牢内",		"lv":2,]),
(["type":3,	"id":"/d/yanjing/liangziweng",	"name":"梁子翁居处",	"lv":2,]),
(["type":3,	"id":"/d/taiwan/house",		"name":"渔夫的家",		"lv":3,]),
(["type":3,	"id":"/d/taiwan/tree4",		"name":"风波林",		"lv":3,]),
(["type":3,	"id":"/d/taiwan/zhuanyuan",	"name":"庄家老屋",		"lv":3,]),
(["type":3,	"id":"/d/taiwan/xiaolou",		"name":"依红楼",		"lv":3,]),
(["type":3,	"id":"/d/taiwan/boss",		"name":"巨大山洞",		"lv":3,]),
(["type":3,	"id":"/d/dali/wfdating",		"name":"镇南王府大厅",	"lv":2,]),
(["type":3,	"id":"/d/dali/chahua1",		"name":"茶花园门",		"lv":2,]),
(["type":3,	"id":"/d/zhongzhou/fuwu",		"name":"休闲中心大堂",	"lv":2,]),
(["type":3,	"id":"/d/zhongzhou/yanguan",	"name":"鸦片馆",		"lv":2,]),
(["type":3,	"id":"/d/zhongzhou/liwu",		"name":"漕帮里屋",		"lv":2,]),
(["type":3,	"id":"/d/mingjiao/xuantianshi",	"name":"悬天石",		"lv":1,]),
(["type":3,	"id":"/d/mingjiao/hsqting",	"name":"洪水旗大厅",	"lv":1,]),
(["type":3,	"id":"/d/mingjiao/qiandian",	"name":"明教前殿",		"lv":3,]),
(["type":3,	"id":"/d/mingjiao/dadian",		"name":"明教大殿",		"lv":4,]),
(["type":3,	"id":"/d/mingjiao/tan",		"name":"碧水潭畔",		"lv":4,]),

});

mapping *renwu4=({
([	"type":1,	"id":"ouyang feng",	"name":"欧阳锋",	"lv":4,	]),
([	"type":1,	"id":"dongfang bubai","name":"东方不败","lv":6,	]),
([	"type":1,	"id":"fan song",	"name":"范松",	"lv":3,	]),
 ([      "type":1,       "id":"snake",           "name":"黑冠巨蟒",      "lv":1, ]),
([	"type":1,	"id":"xiang wentian","name":"向问天",	"lv":4,	]),
([	"type":1,	"id":"zhang chengfeng","name":"张乘风",	"lv":3,	]),
([	"type":1,	"id":"zhang chengyun","name":"张乘云",	"lv":3,	]),
([	"type":1,	"id":"zhao he",	"name":"赵鹤",	"lv":3,	]),
([	"type":1,	"id":"yue buqun",	"name":"岳不群",	"lv":3,	]),
([	"type":1,	"id":"cheng buyou",	"name":"成不忧",	"lv":2,	]),
([	"type":1,	"id":"cong buqi",	"name":"丛不弃",	"lv":2,	]),
//([      "type":1,       "id":"feng buping",     "name":"封不平",        "lv":2, ]),^M
//fix lxh have'n npc
([	"type":1,	"id":"zuo lengchan","name":"左冷禅",	"lv":3,	]),
([	"type":1,	"id":"yuji zi",	"name":"玉玑子",	"lv":1,	]),
([	"type":1,	"id":"yuqing zi",	"name":"玉磬子",	"lv":2,	]),
([	"type":1,	"id":"yuyin zi",	"name":"玉音子",	"lv":2,	]),
([	"type":1,	"id":"caizhu",	"name":"张财主",	"lv":1,	]),
([	"type":1,	"id":"dongming zi",	"name":"洞冥子",	"lv":4,	]),
([	"type":1,	"id":"zong wangshi","name":"宗王师",	"lv":2,	]),
([	"type":1,	"id":"zong wuwei",	"name":"宗无畏",	"lv":4,	]),
([	"type":1,	"id":"mei chaofeng","name":"梅超风",	"lv":1,	]),
([	"type":1,	"id":"yu popo",	"name":"余婆婆",	"lv":1,	]),
([	"type":1,	"id":"tong lao",	"name":"天山童姥",	"lv":6,	]),
([	"type":1,	"id":"ao bai",	"name":"鳌拜",	"lv":1,	]),
([	"type":1,	"id":"wu laoda",	"name":"乌老大",	"lv":1,	]),

([	"type":1,	"id":"miejue shitai",	"name":"灭绝师太",	"lv":4,	]),
//([      "type":1,       "id":"tian qin",                "name":"天禽",  "lv":3, ]),
([	"type":1,	"id":"duan zhengchun",	"name":"段正淳",	"lv":3,	]),
([	"type":1,	"id":"bai suzhen",		"name":"白素贞",	"lv":2,	]),
([	"type":1,	"id":"fahai",			"name":"法海和尚",	"lv":3,	]),
([	"type":1,	"id":"shilong",		"name":"石龙",	"lv":2,	]),
([	"type":1,	"id":"hua hegen",		"name":"华赫艮",	"lv":1,	]),
([	"type":1,	"id":"gao shengtai",	"name":"高升泰",	"lv":2,	]),
([	"type":1,	"id":"dingjing shitai",	"name":"定静师太",	"lv":2,	]),
([	"type":1,	"id":"dingxian shitai",	"name":"定闲师太",	"lv":3,	]),
([	"type":1,	"id":"dingyi shitai",	"name":"定逸师太",	"lv":2,	]),
([	"type":1,	"id":"duo long",		"name":"多隆",	"lv":1,	]),
([	"type":1,	"id":"xu tianchuan",	"name":"徐天川",	"lv":1,	]),
([	"type":1,	"id":"xuan zhen",		"name":"玄真道长",	"lv":3,	]),
([	"type":1,	"id":"chen jinnan",		"name":"陈近南",	"lv":6,	]),
([	"type":1,	"id":"ai laozhe",		"name":"华山矮老者","lv":2,	]),
([	"type":1,	"id":"gao laozhe",		"name":"华山高老者","lv":3,	]),
([	"type":1,	"id":"feng qingyang",	"name":"风清扬",	"lv":6,	]),
([	"type":1,	"id":"ning zhongze",	"name":"宁中则",	"lv":2,	]),
([	"type":1,	"id":"chen jialuo",		"name":"陈家洛",	"lv":1,	]),
([	"type":1,	"id":"jiansi seng",		"name":"监寺僧人",	"lv":3,	]),
([	"type":1,	"id":"lu zhisheng",		"name":"鲁智深",	"lv":2,	]),
([	"type":1,	"id":"wang chao",		"name":"王朝",	"lv":1,	]),
([	"type":1,	"id":"ma han",		"name":"马汉",	"lv":1,	]),
([	"type":1,	"id":"hong qigong",		"name":"洪七公",	"lv":6,	]),
([	"type":1,	"id":"heibai zi",		"name":"黑白子",	"lv":1,	]),
([	"type":1,	"id":"huangzhong gong",	"name":"黄钟公",	"lv":2,	]),
([	"type":1,	"id":"boer shu",		"name":"博尔术",	"lv":3,	]),
([	"type":1,	"id":"guo jing",		"name":"郭靖",	"lv":2,	]),
([	"type":1,	"id":"ke zhene",		"name":"柯镇恶",	"lv":3,	]),
([	"type":1,	"id":"qin bing",		"name":"巡逻亲兵",	"lv":1,	]),
([	"type":1,	"id":"jinwei bing",		"name":"近卫兵",	"lv":1,	]),
([	"type":1,	"id":"zhe bie",		"name":"哲别",	"lv":3,	]),
([      "type":1,       "id":"zhu cong", "name":"朱聪",         "lv":3,   ]),
([	"type":1,	"id":"feng qingyang",	"name":"风清扬",	"lv":6,	]),
([	"type":1,	"id":"ning zhongze",	"name":"宁中则",	"lv":2,	]),
([	"type":1,	"id":"chen jialuo",		"name":"陈家洛",	"lv":1,	]),
([	"type":1,	"id":"jiansi seng",		"name":"监寺僧人",	"lv":3,	]),
([	"type":1,	"id":"lu zhisheng",		"name":"鲁智深",	"lv":2,	]),
([	"type":1,	"id":"wang chao",		"name":"王朝",	"lv":1,	]),
([	"type":1,	"id":"ma han",		"name":"马汉",	"lv":1,	]),
([	"type":1,	"id":"hong qigong",		"name":"洪七公",	"lv":6,	]),
([	"type":1,	"id":"heibai zi",		"name":"黑白子",	"lv":1,	]),
([	"type":1,	"id":"huangzhong gong",	"name":"黄钟公",	"lv":2,	]),
([	"type":1,	"id":"boer shu",		"name":"博尔术",	"lv":3,	]),
([	"type":1,	"id":"guo jing",		"name":"郭靖",	"lv":2,	]),
([	"type":1,	"id":"ke zhene",		"name":"柯镇恶",	"lv":3,	]),
([	"type":1,	"id":"qin bing",		"name":"巡逻亲兵",	"lv":1,	]),
([	"type":1,	"id":"jinwei bing",		"name":"近卫兵",	"lv":1,	]),
([	"type":1,	"id":"zhe bie",		"name":"哲别",	"lv":3,	]),
([	"type":1,	"id":"zhu cong",		"name":"朱聪",	"lv":3,	]),
([	"type":1,	"id":"yang xiao",		"name":"杨逍",	"lv":2,	]),
([	"type":1,	"id":"fan yao",		"name":"范遥",	"lv":2,	]),
([	"type":1,	"id":"wang chongyang",	"name":"王重阳",	"lv":6,	]),
([	"type":1,	"id":"hao datong",		"name":"郝大通",	"lv":1,	]),
([	"type":1,	"id":"liu chuxuan",		"name":"刘处玄",	"lv":1,	]),
([	"type":1,	"id":"ma yu",			"name":"马钰",	"lv":2,	]),
([	"type":1,	"id":"qiu chuji",		"name":"丘处机",	"lv":2,	]),
([      "type":1,	"id":"hong qigong",	"name":"洪七公",        "lv":6,]),
([	"type":1,	"id":"heibai zi",		"name":"黑白子",	"lv":1,	]),
([	"type":1,	"id":"huangzhong gong",	"name":"黄钟公",	"lv":2,	]),
([	"type":1,	"id":"boer shu",		"name":"博尔术",	"lv":3,	]),
([	"type":1,	"id":"guo jing",		"name":"郭靖",	"lv":2,	]),
([	"type":1,	"id":"ke zhene",		"name":"柯镇恶",	"lv":3,	]),
([	"type":1,	"id":"qin bing",		"name":"巡逻亲兵",	"lv":1,	]),
([	"type":1,	"id":"jinwei bing",		"name":"近卫兵",	"lv":1,	]),
([	"type":1,	"id":"zhe bie",		"name":"哲别",	"lv":3,	]),
([	"type":1,	"id":"zhu cong",		"name":"朱聪",	"lv":3,	]),
([	"type":1,	"id":"yang xiao",		"name":"杨逍",	"lv":2,	]),
([	"type":1,	"id":"fan yao",		"name":"范遥",	"lv":2,	]),
([	"type":1,	"id":"wang chongyang",	"name":"王重阳",	"lv":6,	]),
([	"type":1,	"id":"hao datong",		"name":"郝大通",	"lv":1,	]),
([	"type":1,	"id":"liu chuxuan",		"name":"刘处玄",	"lv":1,	]),
([	"type":1,	"id":"ma yu",			"name":"马钰",	"lv":2,	]),
([	"type":1,	"id":"qiu chuji",		"name":"丘处机",	"lv":2,	]),
([	"type":1,	"id":"sun buer",		"name":"孙不二",	"lv":2,	]),
([	"type":1,	"id":"tan chuduan",		"name":"谭处端",	"lv":1,	]),
([	"type":1,	"id":"wang chuyi",		"name":"王处一",	"lv":2,	]),
([	"type":1,	"id":"murong fu",		"name":"慕容复",	"lv":2,	]),
([	"type":1,	"id":"murong bo",		"name":"慕容博",	"lv":6,	]),
([	"type":1,	"id":"tianmen daoren",	"name":"天门道人",	"lv":3,	]),
([	"type":1,	"id":"zhang sanfeng",	"name":"张三丰",	"lv":6,	]),
([	"type":1,	"id":"oldman",		"name":"长须老者",	"lv":2,	]),
([	"type":1,	"id":"hua wuxie",		"name":"花无邪",	"lv":1,	]),
([	"type":1,	"id":"luoyan master",	"name":"落雁老人",	"lv":4,	]),
([	"type":1,	"id":"shangren",		"name":"雪山上人",	"lv":1,	]),
([	"type":1,	"id":"tie qiaosan",		"name":"铁桥三",	"lv":2,	]),
([	"type":1,	"id":"zhengbanqiao",	"name":"郑板桥",	"lv":2,	]),
([	"type":1,	"id":"zhou zhiruo",	"name":"周芷若",	"lv":4,	]),
([	"type":1,	"id":"zhang wuji",	"name":"张无忌",	"lv":6,	]),

([	"type":2,	"id":"tianxiang gao","name":HIC"天香断续膏"NOR,	"lv":2,]),
([	"type":2,	"id":"beike",			"name":"贝壳",		"lv":2,]),
([	"type":2,	"id":"wucai beike",		"name":"五彩贝壳",		"lv":2,]),
([	"type":2,	"id":"yu",			"name":HIC"青龙碧血玉"NOR,	"lv":3,]),
([	"type":2,	"id":"dodge book",		"name":"〖基本步法〗",	"lv":2,]),
([	"type":2,	"id":"duan tielian",	"name":"断开的铁链",	"lv":2,]),
([	"type":2,	"id":"fo chuan",		"name":"檀木佛串",		"lv":3,]),
([	"type":2,	"id":"force book",		"name":"〖内功心诀〗",	"lv":2,]),
([	"type":2,	"id":"skirt",			"name":"百褶裙",		"lv":1,]),
([	"type":2,	"id":"cloth",			"name":"月白缁衣",		"lv":1,]),
([	"type":2,	"id":"hanyue blade",	"name":HIG"寒月斩"NOR,	"lv":3,]),
([	"type":2,	"id":"lengyue blade",	"name":HIG"冷月斩"NOR,	"lv":3,]),
([	"type":2,	"id":"guozi",			"name":HIR"珊瑚果"NOR,	"lv":3,]),
//([      "type":2,       "id":"sword book",              "name":"〖无名剑诀〗",  "lv":2,]),
//fix lxh
([	"type":2,	"id":"skirt",			"name":YEL"虎皮短裙"NOR,	"lv":1,]),
([	"type":2,	"id":"green ruyi",		"name":"绿如意",		"lv":2,]),
([	"type":2,	"id":"baichou san",		"name":"白绸伞",		"lv":3,]),
([	"type":2,	"id":"skirt",			"name":"素白长裙",		"lv":1,]),
([	"type":2,	"id":"jiasha",		"name":"大红袈裟",		"lv":2,]),
([	"type":2,	"id":"hua lan",		"name":"细编翠竹花蓝",	"lv":1,]),
([	"type":2,	"id":"heimu ling",		"name":"黑木令",		"lv":4,]),
([	"type":2,	"id":"kuihua baodian",	"name":"葵花宝典",		"lv":4,]),
([	"type":2,	"id":"cloth",			"name":"红绸小衫",		"lv":5,]),
([	"type":2,	"id":"leizhen dang",	"name":"雷震挡",		"lv":3,]),
([	"type":2,	"id":"shutong gun",		"name":"熟铜棍",		"lv":2,]),
([	"type":2,	"id":"zhen",			"name":"绣花针",		"lv":2,]),
([	"type":2,	"id":"yang qin",		"name":HIC"扬琴"NOR,	"lv":2,]),
([	"type":2,	"id":"fochuan",		"name":"紫檀佛串",		"lv":3,]),
([	"type":2,	"id":"jia sha",		"name":"护法袈裟",		"lv":2,]),
([	"type":2,	"id":"jiangjunzhang",	"name":"将军杖",		"lv":2,]),
([	"type":2,	"id":"pomodao",		"name":"泼墨刀",		"lv":2,]),
([	"type":2,	"id":"qixianjian",		"name":"七弦剑",		"lv":2,]),
([	"type":2,	"id":"weiqizi",		"name":"围棋子",		"lv":2,]),
([	"type":2,	"id":"kulou tougu",		"name":"骷髅头骨",		"lv":2,]),
([	"type":2,	"id":"jindao",		"name":YEL"金刀"NOR,	"lv":3,]),
([	"type":2,	"id":"gang ci",		"name":"峨嵋钢刺",		"lv":2,]),
([	"type":2,	"id":"kulou",			"name":"白骨骷髅",		"lv":2,]),
([	"type":2,	"id":"hammer",		"name":"流星锤",		"lv":3,]),
([	"type":2,	"id":"taoguan",		"name":"陶罐",		"lv":1,]),
([	"type":2,	"id":"qingci wan",		"name":"青瓷碗",		"lv":1,]),
([	"type":2,	"id":"fuping",		"name":HIG"浮萍"NOR,	"lv":1,]),
([	"type":2,	"id":"zijin chui",		"name":"紫金锤",		"lv":2,]),
([	"type":2,	"id":"tuling zhu",		"name":"土灵珠",		"lv":6,]),
([	"type":2,	"id":"cloth",			"name":"公子衫",		"lv":3,]),
([	"type":2,	"id":"yemingzhu",		"name":HIC"夜明珠"NOR,	"lv":2,]),
([	"type":2,	"id":"youming jian",	"name":RED"幽冥剑"NOR,	"lv":3,]),
([	"type":2,	"id":"boot",			"name":HIY"绣金福字屐"NOR,	"lv":3,]),
([	"type":2,	"id":"shu",			"name":"拳谱总诀",		"lv":2,]),
([	"type":2,	"id":"bishuijian",		"name":"碧水剑",		"lv":3,]),
([	"type":2,	"id":"pao",			"name":"白色道袍",		"lv":2,]),
([	"type":2,	"id":"biyuzan",		"name":HIG"碧玉簪"NOR,	"lv":2,]),
([	"type":2,	"id":"wangguo",		"name":HIG"忘魂果"NOR,	"lv":3,]),
([	"type":2,	"id":"wushuang_jian",	"name":HIM"无双神剑"NOR,	"lv":3,]),
([	"type":2,	"id":"yuchang",		"name":HIC"鱼肠剑"NOR,	"lv":3,]),
([	"type":2,	"id":"zijindan",		"name":"紫金活络丹",	"lv":2,]),
([	"type":2,	"id":"jinbanfu",		"name":"金板斧",		"lv":2,]),
([	"type":2,	"id":"wujinfu",		"name":RED"乌金斧"NOR,	"lv":3,]),
([	"type":2,	"id":"xingfengdao",		"name":"腥风刀",		"lv":2,]),
([	"type":2,	"id":"yinbanfu",		"name":"银板斧",		"lv":3,]),
([	"type":2,	"id":"zijindao",		"name":MAG"紫金刀"NOR,	"lv":3,]),
([	"type":2,	"id":"boyu",			"name":"紫金钵盂",		"lv":2,]),
([	"type":2,	"id":"songmo",		"name":"宋墨",		"lv":2,]),
([	"type":2,	"id":"stone",			"name":"晶石",		"lv":3,]),
([	"type":2,	"id":"leaf",			"name":RED"僳潞叶"NOR,	"lv":2,]),
([	"type":2,	"id":"taozi",			"name":"弥猴桃",		"lv":1,]),
([	"type":2,	"id":"hailuo",		"name":"海螺",		"lv":1,]),
([	"type":2,	"id":"skirt",			"name":"花短褂",		"lv":1,]),
([	"type":2,	"id":"chui huoguan",	"name":"吹火管",		"lv":2,]),
([	"type":2,	"id":"sipao",			"name":"丝袍",		"lv":1,]),
([	"type":2,	"id":"skirt",			"name":"石榴裙",		"lv":2,]),
([	"type":2,	"id":"zhenzhu",		"name":"珍珠项链",		"lv":1,]),
([	"type":2,	"id":"cloth",			"name":"雪白长衫",		"lv":2,]),
([	"type":2,	"id":"xiangjiu",		"name":"苏合香酒",		"lv":1,]),
([	"type":2,	"id":"powan",			"name":"破碗",		"lv":2,]),
([	"type":2,	"id":"jin he",		"name":"锦盒",		"lv":1,]),
([	"type":2,	"id":"yaofang",		"name":"残破药方",		"lv":2,]),
([	"type":2,	"id":"huang",			"name":"黄精",		"lv":1,]),

(["type":3,	"id":"/d/chengdu/wenzai/xiaodao",	"name":"湖心小岛",		"lv":3,]),
(["type":3,	"id":"/d/emei/gate",		"name":"凤凰坪",		"lv":2,]),
(["type":3,	"id":"/d/emei/ningcui",		"name":"凝翠楼",		"lv":2,]),
(["type":3,	"id":"/d/emei/qixiang",		"name":"七香轩",		"lv":2,]),
(["type":3,	"id":"/d/emei/huaying",		"name":"花影亭",		"lv":2,]),
(["type":3,	"id":"/d/emei/ligouyuan",		"name":"离垢园",		"lv":2,]),
(["type":3,	"id":"/d/emei/huayantin",		"name":"华严宝塔亭",	"lv":2,]),
(["type":3,	"id":"/d/emei/hongchun",		"name":"洪椿坪",		"lv":2,]),
(["type":3,	"id":"/d/emei/dongzhong",		"name":"九老仙府",		"lv":3,]),
(["type":3,	"id":"/d/emei/tianju",		"name":"天心居",		"lv":3,]),
(["type":3,	"id":"/d/hainan/xuanya",		"name":"悬崖秘洞",		"lv":2,]),
(["type":3,	"id":"/d/hainan/cave3",		"name":"落笔洞",		"lv":2,]),
(["type":3,	"id":"/d/hainan/underhill",	"name":"琼崖下",		"lv":2,]),
(["type":3,	"id":"/d/hainan/baiyunan",		"name":"白云庵",		"lv":2,]),
(["type":3,	"id":"/d/hainan/shutang",		"name":"白云庵藏经堂",	"lv":4,]),
(["type":3,	"id":"/d/hainan/chucang",		"name":"白云庵储藏室",	"lv":4,]),
(["type":3,	"id":"/d/heimuya/chengdedian",	"name":"成德殿",		"lv":3,]),
(["type":3,	"id":"/d/heimuya/neishi",		"name":"小舍内室",		"lv":4,]),
(["type":3,	"id":"/d/hengshan/xuankong1",	"name":"悬空寺北楼",	"lv":2,]),
(["type":3,	"id":"/d/hengshan/cuipinggu2",	"name":"翠屏谷",		"lv":2,]),
(["type":3,	"id":"/d/hengshan/sanjiaodian",	"name":"三教殿",		"lv":2,]),
(["type":3,	"id":"/d/hengshan/yunge",		"name":"云阁虹桥",		"lv":2,]),
(["type":3,	"id":"/d/hengshan/xuangengsong",	"name":"悬根松",		"lv":2,]),
(["type":3,	"id":"/d/hengshan/tongyuangu",	"name":"通元谷",		"lv":3,]),
(["type":3,	"id":"/d/hengshan/jijiaoshi",	"name":"鸡叫石",		"lv":3,]),
(["type":3,	"id":"/d/hengshan/kutianjing",	"name":"苦甜井",		"lv":3,]),
(["type":3,	"id":"/d/hengshan/huixiantai",	"name":"会仙台",		"lv":3,]),
(["type":3,	"id":"/d/huanggon/houtang1",	"name":"香堂",		"lv":3,]),
(["type":3,	"id":"/d/japan/liushengfu",	"name":"柳生府",		"lv":2,]),
(["type":3,	"id":"/d/japan/xiangpu",		"name":"土肥原相扑屋",	"lv":2,]),
(["type":3,	"id":"/d/japan/shuwu",		"name":"朝野书屋",		"lv":2,]),
(["type":3,	"id":"/d/japan/haixian",		"name":"海鲜馆",		"lv":2,]),
(["type":3,	"id":"/d/japan/yijiguan",		"name":"艺妓馆",		"lv":2,]),
(["type":3,	"id":"/d/japan/qingzhou",		"name":"清州城",		"lv":2,]),
(["type":3,	"id":"/d/japan/dongmen",		"name":"神户东门",		"lv":2,]),
(["type":3,	"id":"/d/lingjiu/xianchou",	"name":"仙愁门",		"lv":2,]),
(["type":3,	"id":"/d/lingjiu/dating",		"name":"独尊厅",		"lv":2,]),
(["type":3,	"id":"/d/lingjiu/biguan",		"name":"闭关室",		"lv":2,]),
(["type":3,	"id":"/d/lingjiu/mishi",		"name":"独尊密室",		"lv":2,]),
(["type":3,	"id":"/d/lingjiu/wuqiku",		"name":"蓼风轩",		"lv":2,]),
(["type":3,	"id":"/d/lingjiu/liangong",	"name":"戏凤阁",		"lv":2,]),
(["type":3,	"id":"/d/lingjiu/chufang",		"name":"藕香榭",		"lv":2,]),
(["type":3,	"id":"/d/lingjiu/qiushi",		"name":"囚室",		"lv":2,]),
(["type":3,	"id":"/d/lingjiu/xuanbing",	"name":"玄冰室",		"lv":2,]),
(["type":3,	"id":"/d/lingjiu/caifeng",		"name":"潇湘馆",		"lv":2,]),
(["type":3,	"id":"/d/meizhuang/heilao",	"name":"湖底黑牢",		"lv":4,]),
(["type":3,	"id":"/d/quanzhen/xiaohuayuan1",	"name":"重阳园",		"lv":2,]),
(["type":3,	"id":"/d/quanzhen/shandong",	"name":"后山山洞",		"lv":2,]),
(["type":3,	"id":"/d/quanzhen/mishi",		"name":"全真密室",		"lv":2,]),
(["type":3,	"id":"/d/songshan/chanyuan",	"name":"峻极禅院",		"lv":2,]),
(["type":3,	"id":"/d/taiwan/house",		"name":"渔夫的家",		"lv":2,]),
(["type":3,	"id":"/d/taiwan/tree4",		"name":"风波林",		"lv":2,]),
(["type":3,	"id":"/d/taiwan/zhuanyuan",	"name":"庄家老屋",		"lv":2,]),
(["type":3,	"id":"/d/taiwan/xiaolou",		"name":"依红楼",		"lv":3,]),
(["type":3,	"id":"/d/taiwan/boss",		"name":"巨大山洞",		"lv":3,]),
(["type":3,	"id":"/d/yeyangzai/da",		"name":"野羊寨寨主室",	"lv":3,]),
(["type":3,	"id":"/d/yeyangzai/lu4",		"name":"野羊寨库房",	"lv":3,]),
(["type":3,	"id":"/d/huanggon/shiwu",		"name":"石牢",		"lv":2,]),
(["type":3,	"id":"/d/zhongzhou/fuwu",		"name":"休闲中心大堂",	"lv":2,]),
(["type":3,	"id":"/d/zhongzhou/yanguan",	"name":"鸦片馆",		"lv":2,]),
(["type":3,	"id":"/d/zhongzhou/liwu",		"name":"漕帮里屋",		"lv":2,]),
(["type":3,	"id":"/d/chengdu/wenzai/dating",	"name":"温家大厅",		"lv":2,]),
(["type":3,	"id":"/d/mingjiao/qiandian",	"name":"明教前殿",		"lv":3,]),
(["type":3,	"id":"/d/mingjiao/dadian",		"name":"明教大殿",		"lv":4,]),
(["type":3,	"id":"/d/mingjiao/tan",		"name":"碧水潭畔",		"lv":4,]),

});
